In [13]:
del streamflow_stat_plots

In [1]:
import numpy as np
import pandas as pd
import requests
import os
import glob
import datetime as datetime
from dataIO import dataloader, webservices
# from dataIO.webservices import fetch_ca_water_data
from statisticscalculator import generalstatistics, climatestatistics
from plot_collection import stackedlineplots, streamflow_stat_plots, streamflow_stat_plots_matplotlib
import plotly.express as px
from plotly import graph_objects as go

In [2]:
import io

def fetch_ca_water_data(start_date, end_date, stations, parameters):
    base_url = 'https://wateroffice.ec.gc.ca/services/daily_data/csv/inline'
    
    # Format station and parameter lists for URL query parameters
    station_params = '&'.join([f'stations[]={station}' for station in stations])
    parameter_params = '&'.join([f'parameters[]={parameter}' for parameter in parameters])
    
    # Construct the complete URL with parameters
    url = f'{base_url}?{station_params}&{parameter_params}&start_date={start_date}&end_date={end_date}'
    
    # Send HTTP GET request to fetch data
    response = requests.get(url)
    
    # Check if request was successful
    if response.status_code == 200:
        # Read CSV data directly from response content
        data = pd.read_csv(io.StringIO(response.content.decode('utf-8')))
        return data
    else:
        print(f"Failed to fetch data. Status code: {response.status_code}")
        return None

In [3]:
headwater = pd.read_excel('headwater_sites_revised.xlsx')
headwater.set_index('site_no', inplace=True)
site_list = list(headwater.index)
lats = list(headwater['lat'])
longs = list(headwater['long']) 


all_site_data = {}
for site in site_list:
    try:
        # basin = site[1][1]
        data = webservices.usgs_streamflow().get_data(start_date='1968-10-01', end_date='2023-10-01',sites=str(site)).reset_index()
        all_site_data[site] = data
    except Exception as e:
        print(e)
    finally:
        pass

https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12301250&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12302055&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12304500&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12306500&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12324400&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12324590&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12332000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12335100&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12342500&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12344000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12359800&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12370000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12411000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12413875&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12414900&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12415135&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12442500&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12448500&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12451000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12452990&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=12456500&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13011900&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13015000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13027500&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13046995&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13052200&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13058000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13063000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13073000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13140335&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13181000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13185000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13186000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13235000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13258500&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13302005&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13305310&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13307000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13310700&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13336500&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13337000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13338500&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=13340600&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14038530&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14044000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14048000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14087380&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14091500&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14093000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14097100&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14101500&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14139800&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14159200&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14161500&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14178000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14179000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14180300&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14185000&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060
https://waterservices.usgs.gov/nwis/dv/?format=json&sites=14185900&startDT=1968-10-01&endDT=2023-10-01&siteStatus=all&parameterCd=00060

In [4]:
import sqlite3
conn = sqlite3.connect('BC Data/Hydat.sqlite3')
cursor = conn.cursor()
sql_statement = "SELECT * FROM sqlite_master WHERE type='table';"
cursor.execute(sql_statement)
tables = cursor.fetchall()
# for table in tables:
#     print(table[2])

canadian_stations = [
    '08LD001', '07EA007', '08NL004','09AA006','08FB006','08EC001','08EC013','08KE016','08LB020','08LB069','07FC001',
    '08FB007','08MB006','08NE039','08NB012','08LB038','07FC003','10CD004','08KD007','08EE013','08NN002','07FA005',
    '08ND012','08NB014','08NH130','08KB001','08KA007','08KA005','08KA004','08NK018','08NP001','07FB009','07EA005',
    '08EG012','08NK016','08NK002','08GA071','08LE024','08NH119','08JD006','08EE004','08EE003','08NC004','08GA072',
    '08MG001','08HA001','08MB005','08MA002','08MA001','08MH103','08MH016','08MH001','07EE009','08LA001','08LG048',
    '08NB005','08NA002','10AC005','08FC003','08KA001','08JD006','08NH119','08LE024','08GA071','08NK002','08NK016',
    '08EG012','07EA005','07FB009','08NP001','08NK018','08KA004','08KA005','08KA007','08KB001','08NH130','08NB014',
    '08ND012','07FA005','08NN002'
]
parameters = ['flow']

all_ca_site_data = fetch_ca_water_data(start_date='1968-10-01', end_date='2023-10-01', stations=canadian_stations, parameters=parameters)

query = """
    SELECT STATION_NUMBER, STATION_NAME, PROV_TERR_STATE_LOC, LATITUDE, LONGITUDE, DRAINAGE_AREA_GROSS FROM STATIONS 
    WHERE STATION_NUMBER IN ({})
""".format(','.join(['?']*len(canadian_stations)))

cursor.execute(query, canadian_stations)
station_meta_data = cursor.fetchall()
print(len(canadian_stations))
station_meta_data=pd.DataFrame(station_meta_data)
station_meta_data.columns = ['STATION_NUMBER', 'STATION_NAME', 'PROV_TERR_STATE_LOC', 'LATITUDE', 'LONGITUDE', 'DRAINAGE_AREA_GROSS']
# station_meta_data
# if all_ca_site_data is not None:
#     all_ca_site_data.head()

80

In [5]:
mf_flows = pd.read_excel('mf_flows_appendix_a_w_loc.xlsx')
mf_flows.rename(columns={'Lat':'Long', 'Long':'Lat'}, inplace=True)
mf_flows.set_index('ID', inplace=True) # chaining .set_index() apparently doesn't work.
mf_flows.head(3)

,Name,Basin,Long,Lat,Section,H,S,A,L,ARF,D,DD,E,EE,M
ID,,,,,,,,,,,,,,,
ALF,Albeni Falls,Pend Oreille,-117.030000,48.180000,3.2,x,x,x,x,x,x,x,NaN,NaN,NaN
ANA,Anatone,Lower Snake,-116.976667,46.097222,3.5,x,x,x,x,x,NaN,NaN,NaN,NaN,NaN
BIT,Bitterroot,Pend Oreille,-114.050000,46.830000,3.2,x,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
modified_flows_m = {}

for file in glob.glob('modifiedflows2020/m_files/*'):
    # print(file)
    filename = file.split('/')[2]
    sitename = filename.split('_')[0]
    # print(sitename[:3])
    # print(mf_flows['ID'])
    if sitename[:3] in mf_flows.index.to_list():
        df = pd.read_excel(file)
        # print(sitename[:3])
        modified_flows_m[sitename] = df
# print(len(modified_flows_m.keys()))

In [ ]:
# a = str(pd.to_datetime('1960-10-01').date())
# b = str(pd.to_datetime('2018-10-10').date())
# f_ca[f_ca['Date'].between(a, b)]

In [33]:
# d = dataloader.DataLoader(filtered_all_ca_site_data.get('07EE009'), 'Date', 'Value/Valeur')

In [7]:
# filtered_df = all_site_data.get(site)[all_site_data.get(site)['Date']].between(start_date, end_date)

In [6]:
end_date = '2018-10-01'
start_dates = [
#     '1938-10-01', 
#     '1948-10-01', 
    '1968-10-01',
#     '1975-10-01',
    # '1978-10-01',
    # '1988-10-01',
    # '1998-10-01', 
#     '2010-10-01', 
#     '2018-10-01', 
]
figs_hw = []
figs_ca = []
figs_mf = []
for start_date in start_dates:
# for start_date, end_date in zip(start_dates, end_dates):

###-------USGS gages/Headwater sites-----------------------------
#     file_name = f'Headwater_MK_Results_{start_date}to{end_date}.html'
    # try:
    start_date = pd.to_datetime(start_date).date()
    end_date = pd.to_datetime(end_date).date()
    filtered_all_site_data = {}
    yrs_of_data = []
    included_sites = []
    excluded_sites = []
    for site, df in all_site_data.items():
        # num_yrs_of_data = len(df['Date'])/365
        # yrs_of_data.append(num_yrs_of_data)
    
        filtered_df = all_site_data.get(site)[all_site_data.get(site)['Date'].between(start_date, end_date)]
        #if more than 15% of data is missing during the time period, exclude station
        if ((end_date - start_date).days * 0.85) > len(filtered_df['Discharge']):
            print(f"Site {site} is missing more than 15% of data between {start_date} and {end_date}.  It will NOT be included in the study.")
            excluded_sites.append(site)
        else:
            filtered_all_site_data[site] = filtered_df
            print(f'Site {site} has more than 85% of data between {start_date} and {end_date} and will be included in the study.')
            included_sites.append(site)
    
    volume_stats = {}
    print(f'Number of included headwater sites: {len(included_sites)}')
    print(f'Number of headwater sites excluded from study: {len(excluded_sites)}')
    
    for site, site_df in filtered_all_site_data.items():
        d = dataloader.DataLoader(site_df, 'Date', name_of_Q_column='Discharge')
        s = climatestatistics.Streamflow(d)
      
        try:
            mann_kendall_results = {}
            mann_kendall_results['lat'] = headwater[headwater.index==site].iat[0,1]
            mann_kendall_results['long'] = headwater[headwater.index==site].iat[0,2]
            mann_kendall_results['name'] = headwater[headwater.index==site].iat[0,0]
            
        #     for day in ['01-01', '03-01', '05-01', '08-01']:
            s.calc_runoff_bw_days(begin_month_day='01-01', end_month_day='12-31', alpha=.05)
            # print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            figs_hw.append(runoff_bw_dates_plot)

            s.calc_runoff_bw_days(begin_month_day='01-01', end_month_day='03-31', alpha=.05)
            print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            mann_kendall_results['Winter Vol']=s.volume_bw_days_mann_kendall_test
            figs_hw.append(runoff_bw_dates_plot)


            s.calc_runoff_bw_days(begin_month_day='04-01', end_month_day='07-31', alpha=.05)
            # print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            mann_kendall_results['Runoff Season Vol'] = s.volume_bw_days_mann_kendall_test
            figs_hw.append(runoff_bw_dates_plot)


            s.calc_runoff_bw_days(begin_month_day='08-01', end_month_day='9-30', alpha=.05)
            # print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            mann_kendall_results['Late Summer'] = s.volume_bw_days_mann_kendall_test
            figs_hw.append(runoff_bw_dates_plot)


            s.calc_runoff_bw_days(begin_month_day='10-01', end_month_day='12-31', alpha=.05)
            # print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            mann_kendall_results['Fall'] = s.volume_bw_days_mann_kendall_test
            figs_hw.append(runoff_bw_dates_plot) 
        
#             s.calc_runoff_bw_days(begin_month_day='01-01', end_month_day='01-31', alpha=.05)            
#             mann_kendall_results['Jan']=s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='02-01', end_month_day='02-28', alpha=.05)
#             mann_kendall_results['Feb']=s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='03-01', end_month_day='03-28', alpha=.05)
#             mann_kendall_results['Mar'] = s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='04-01', end_month_day='4-30', alpha=.05)
#             mann_kendall_results['Apr'] = s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='05-01', end_month_day='05-31', alpha=.05)            
#             mann_kendall_results['May']=s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='06-01', end_month_day='06-30', alpha=.05)
#             mann_kendall_results['Jun']=s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='07-01', end_month_day='07-31', alpha=.05)
#             mann_kendall_results['Jul'] = s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='08-01', end_month_day='8-31', alpha=.05)
#             mann_kendall_results['Aug'] = s.volume_bw_days_mann_kendall_test            
#             s.calc_runoff_bw_days(begin_month_day='09-01', end_month_day='09-30', alpha=.05)            
#             mann_kendall_results['Sep']=s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='10-01', end_month_day='10-31', alpha=.05)
#             mann_kendall_results['Oct']=s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='11-01', end_month_day='11-30', alpha=.05)
#             mann_kendall_results['Nov'] = s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='12-01', end_month_day='12-31', alpha=.05)
#             mann_kendall_results['Dec'] = s.volume_bw_days_mann_kendall_test  

#             mann_kendall_results['Site Type'] = 'USGS'
#             volume_stats[site] = mann_kendall_results

        except Exception as e:
            raise ValueError('Saving to volume_stats_hw prob failed')
            print(e)
            

    

# ##-----------Canadian sites---------------            
    # try:
#     start_date = pd.to_datetime(start_date).date()
#     end_date = pd.to_datetime(end_date).date()
    filtered_all_ca_site_data = {}
    yrs_of_data = []
    included_sites = []
    excluded_sites = []
    for site in all_ca_site_data[' ID'].unique(): #station_meta_data['STATION_NUMBER'].unique():
        # num_yrs_of_data = len(df['Date'])/365
        # yrs_of_data.append(num_yrs_of_data)
    #fiiiiiiii
        filtered_df = all_ca_site_data[all_ca_site_data[' ID']==site]
        f_ca = filtered_df
#         pd.to_datetime(filtered_df['Date'])
        filtered_df = filtered_df[filtered_df.loc[:, 'Date'].between(str(start_date), str(end_date))]
#         print(type(filtered_df['Date']))
#         filtered_df.loc[:, 'Date'] = pd.to_datetime(filtered_df.loc[:, 'Date'])
        #if more than 15% of data is missing during the time period, exclude station
        if ((end_date - start_date).days * 0.85) > len(filtered_df['Value/Valeur']):
            print(f"Site {site} is missing more than 15% of data between {start_date} and {end_date}.  It will NOT be included in the study.")
            excluded_sites.append(site)
        else:
            filtered_all_ca_site_data[site] = filtered_df
            print(f'Site {site} has more than 85% of data between {start_date} and {end_date} and will be included in the study.')
            included_sites.append(site)
    
#     volume_stats = {}
#     print(f'Number of included headwater sites: {len(included_sites)}')
#     print(f'Number of headwater sites excluded from study: {len(excluded_sites)}')
    
    for site in all_ca_site_data[' ID'].unique(): #station_meta_data['STATION_NUMBER'].unique():
        print(site)
        try:
            d = dataloader.DataLoader(filtered_all_ca_site_data.get(site), 'Date', 'Value/Valeur')
            s = climatestatistics.Streamflow(d)
#         except:
#             pass
#         try:
            mann_kendall_results = {}
            mann_kendall_results['lat'] = station_meta_data[station_meta_data['STATION_NUMBER']==site]['LATITUDE']
            mann_kendall_results['long'] = station_meta_data[station_meta_data['STATION_NUMBER']==site]['LONGITUDE']
            mann_kendall_results['name'] = station_meta_data[station_meta_data['STATION_NUMBER']==site]['STATION_NAME']
            
            s.calc_runoff_bw_days(begin_month_day='01-01', end_month_day='12-31', alpha=.05)
            # print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            figs_ca.append(runoff_bw_dates_plot)

            s.calc_runoff_bw_days(begin_month_day='01-01', end_month_day='03-31', alpha=.05)
            print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            mann_kendall_results['Winter Vol']=s.volume_bw_days_mann_kendall_test
            figs_ca.append(runoff_bw_dates_plot)


            s.calc_runoff_bw_days(begin_month_day='04-01', end_month_day='07-31', alpha=.05)
            # print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            mann_kendall_results['Runoff Season Vol'] = s.volume_bw_days_mann_kendall_test
            figs_ca.append(runoff_bw_dates_plot)


            s.calc_runoff_bw_days(begin_month_day='08-01', end_month_day='9-30', alpha=.05)
            # print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            mann_kendall_results['Late Summer'] = s.volume_bw_days_mann_kendall_test
            figs_ca.append(runoff_bw_dates_plot)


            s.calc_runoff_bw_days(begin_month_day='10-01', end_month_day='12-31', alpha=.05)
            # print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            mann_kendall_results['Fall'] = s.volume_bw_days_mann_kendall_test
            figs_ca.append(runoff_bw_dates_plot) 
#             s.calc_runoff_bw_days(begin_month_day='01-01', end_month_day='01-31', alpha=.05)            
#             mann_kendall_results['Jan']=s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='02-01', end_month_day='02-28', alpha=.05)
#             mann_kendall_results['Feb']=s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='03-01', end_month_day='03-28', alpha=.05)
#             mann_kendall_results['Mar'] = s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='04-01', end_month_day='4-30', alpha=.05)
#             mann_kendall_results['Apr'] = s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='05-01', end_month_day='05-31', alpha=.05)            
#             mann_kendall_results['May']=s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='06-01', end_month_day='06-30', alpha=.05)
#             mann_kendall_results['Jun']=s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='07-01', end_month_day='07-31', alpha=.05)
#             mann_kendall_results['Jul'] = s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='08-01', end_month_day='8-31', alpha=.05)
#             mann_kendall_results['Aug'] = s.volume_bw_days_mann_kendall_test            
#             s.calc_runoff_bw_days(begin_month_day='09-01', end_month_day='09-30', alpha=.05)            
#             mann_kendall_results['Sep']=s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='10-01', end_month_day='10-31', alpha=.05)
#             mann_kendall_results['Oct']=s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='11-01', end_month_day='11-30', alpha=.05)
#             mann_kendall_results['Nov'] = s.volume_bw_days_mann_kendall_test
#             s.calc_runoff_bw_days(begin_month_day='12-01', end_month_day='12-31', alpha=.05)
#             mann_kendall_results['Dec'] = s.volume_bw_days_mann_kendall_test  
            
            mann_kendall_results['Site Type'] = 'Environmental Canada'
            volume_stats[site] = mann_kendall_results
            
        except Exception as e:
#             raise ValueError('Saving to volume_stats_ca prob failed')
            print('Saving to volume_stats_ca prob failed')
            print(e)
            pass

# volume_stats_df = pd.DataFrame(volume_stats).T
            
# -------Modified Flows----------

    modified_flows_m_filtered_dates = {}
    for k,v in modified_flows_m.items():
#         print(f'dates: {start_date} and {end_date}')
#         print(f'date types: {type(start_date)} and {type(end_date)}')
#         start_date = pd.to_datetime(start_date).date()
#         end_date = pd.to_datetime(end_date).date()
#         print(f'dates: {start_date} and {end_date}')
#         print(f'date types: {type(start_date)} and {type(end_date)}')
#         print(f"type of df data: {type(modified_flows_m.get(k)['date'])}")
        
        start_date = str(start_date)
        end_date = str(end_date)
        
        # modified_flows_m_filtered_dates[k] = modified_flows_m.get(k)[modified_flows_m.get(k)['date']>=start_date]
        modified_flows_m_filtered_dates[k] = modified_flows_m.get(k)[modified_flows_m.get(k)['date'].between(start_date, end_date)]
    
    
    
    volume_stats_mf = {}    
    for site in modified_flows_m_filtered_dates.items():
#         print(site)
        sitename = site[0].split('_')[0]    
        # print(sitename)
        stupid = sitename.split('6')[1]
        # print(stupid)
        name_of_Q_column = f'{stupid} (unit:cfs)'
        # print(name_of_Q_column)
    #     data = webservices.usgs_streamflow().get_data(start_date='1921-10-01', end_date=datetime.datetime.now().strftime('%Y-%m-%d'),sites=str(site[1])).reset_index()
        d = dataloader.DataLoader(site[1], 'date', name_of_Q_column=name_of_Q_column)
        s = climatestatistics.Streamflow(d)
        # print(d._df[d._name_of_Q_column][0])
        site_short = site[0][:3]
        # print(f'Site: {site_short}')
    
        try:
            mann_kendall_results_mf = {}
            
            s.calc_runoff_bw_days(begin_month_day='01-01', end_month_day='12-31', alpha=.05)
            # print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            figs_mf.append(runoff_bw_dates_plot)

            s.calc_runoff_bw_days(begin_month_day='01-01', end_month_day='03-31', alpha=.05)
            print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            mann_kendall_results['Winter Vol']=s.volume_bw_days_mann_kendall_test
            figs_mf.append(runoff_bw_dates_plot)


            s.calc_runoff_bw_days(begin_month_day='04-01', end_month_day='07-31', alpha=.05)
            # print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            mann_kendall_results['Runoff Season Vol'] = s.volume_bw_days_mann_kendall_test
            figs_mf.append(runoff_bw_dates_plot)


            s.calc_runoff_bw_days(begin_month_day='08-01', end_month_day='9-30', alpha=.05)
            # print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            mann_kendall_results['Late Summer'] = s.volume_bw_days_mann_kendall_test
            figs_mf.append(runoff_bw_dates_plot)


            s.calc_runoff_bw_days(begin_month_day='10-01', end_month_day='12-31', alpha=.05)
            # print(f'Mann-Kendall Test Results looking for trend in discharge from {s.begin_month_day} to {s.end_month_day}: {s.volume_bw_days_mann_kendall_test}')
            runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
            runoff_bw_dates_plot.plot_runoff_volume_between_2days(site)
            mann_kendall_results['Fall'] = s.volume_bw_days_mann_kendall_test
            figs_mf.append(runoff_bw_dates_plot)              
#             s.calc_max(calc_from_rolling_median=False, window_size=7)  
#             s.calc_annual_runoff_threshold_day(0.5, alpha=.05)
#             s.calc_runoff_bw_days(begin_month_day='01-01', end_month_day='12-31', alpha=.05)
#             s.calc_runoff_bw_days(begin_month_day='10-01', end_month_day='12-31', alpha=.05)
            
#             runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
#             mann_kendall_results_mf['Fall Vol']=s.volume_bw_days_mann_kendall_test

#             s.calc_runoff_bw_days(begin_month_day='01-01', end_month_day='03-31', alpha=.05)
#             runoff_bw_dates_plot = streamflow_stat_plots.Plot_Runoff_Volume_Between_2Days(s)
#             mann_kendall_results_mf['Winter Vol']=s.volume_bw_days_mann_kendall_test

#             s.calc_runoff_bw_days(begin_month_day='04-01', end_month_day='06-30', alpha=.05)

#             mann_kendall_results_mf['Runoff Season Vol'] = s.volume_bw_days_mann_kendall_test

#             s.calc_runoff_bw_days(begin_month_day='07-01', end_month_day='9-30', alpha=.05)

#             mann_kendall_results_mf['Summer Vol'] = s.volume_bw_days_mann_kendall_test
           
            
#             mann_kendall_results_mf['Q on date of peak Q date MK Test'] = s.rolling_yr_Qmax_mk_test
#             mann_kendall_results_mf['dayofyear on date of peak Q date MK Test'] = s.rolling_yr_DOYmax_mk_test
#             mann_kendall_results_mf['Threshold Vol MK Test'] = s.threshold_vol_mann_kendall_test
#             mann_kendall_results_mf['Threshold Vol DOY MK Test'] = s.threshold_vol_dates_mann_kendall_test
#             mann_kendall_results_mf['Total Vol MK Test'] = s.total_volume_mann_kendall_test
#             # mann_kendall_results['Basin'] = basin
#             mann_kendall_results_mf['lat'] = mf_flows[mf_flows.index==site_short].iat[0,3]
#             mann_kendall_results_mf['long'] = mf_flows[mf_flows.index==site_short].iat[0,2]
#             # print(mann_kendall_results['long'])
#             mann_kendall_results_mf['name'] = mf_flows[mf_flows.index==site_short].iat[0,0]
#             volume_stats_mf[site_short] = mann_kendall_results_mf
#             mann_kendall_results_mf['Site Type'] = 'modified flows'

        except Exception as e:
            raise ValueError('Saving to volume_stats_mf prob failed')
            print(e)
 
    
    
    
    
    
    
    
#     sites = []
#     site_name = []
#     site_type = []
#     lat = []
#     long = []
    
#     months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
#     mk_period_results = {}
#     for month in months:
#         mk_period_results[f'{month}_trend'] = []
#         mk_period_results[f'{month}_h'] = []
#         mk_period_results[f'{month}_p'] = []
#         mk_period_results[f'{month}_tau'] = []
    
    
#     for site, value in volume_stats_hw.items():
        
#         sites.append(site)
#         site_name.append(value.get('name'))
#         site_type.append('headwater')
#         lat.append(value.get('lat'))
#         long.append(value.get('long'))              
                         
# #         for stat, e_list in mk_period_results:
#         for month in months:
#             mk_period_results.get(f'{month}_trend').append(value.get(month)[0])
#             mk_period_results.get(f'{month}_p').append(value.get(month)[2])
#             mk_period_results.get(f'{month}_tau').append(value.get(month)[4])


    
    
    
    
    
 
#     peak_runoffQ = pd.DataFrame({'sites':sites, 'site_name': site_name, 'site_type': site_type, 'lat': lat, 'long': long, 'trend': PeakRunoffQ_trend,  'p': PeakRunoffQ_p, 'tau': PeakRunoffQ_tau})
#     peak_runoffDOY = pd.DataFrame({'sites':sites, 'site_name': site_name, 'site_type': site_type,'lat': lat, 'long': long, 'trend': PeakRunoffDOY_trend,  'p': PeakRunoffDOY_p, 'tau': PeakRunoffDOY_tau})
#     ThresholdVol = pd.DataFrame({'sites':sites, 'site_name': site_name, 'site_type': site_type,'lat': lat, 'long': long, 'trend': ThresholdVol_trend, 'p': ThresholdVol_p, 'tau': ThresholdVol_tau})
#     ThresholdDOY = pd.DataFrame({'sites':sites, 'site_name': site_name, 'site_type': site_type,'lat': lat, 'long': long, 'trend': ThresholdDOY_trend, 'p': ThresholdDOY_p, 'tau': ThresholdDOY_tau})
#     total_vol = pd.DataFrame({'sites':sites, 'site_name': site_name, 'site_type': site_type,'lat': lat, 'long': long, 'trend': TotalVol_trend, 'p': TotalVol_p, 'tau': TotalVol_tau})

#     peak_runoffQ_title = 'Trend in Peak Runoff Volume: Mann-Kendall Test Results' 
#     peak_runoffDOY_title = 'Trend in Timing During Peak Runoff: Mann-Kendall Test Results'
#     ThresholdDOY_title = 'Trends in Timing of 50% Yearly Volume: Mann-Kendall Test Results'
#     ThresholdVol_title = 'Trend in Volume at 50% Yearly Flow: Mann-Kendall Test Results'
#     total_vol_title = 'Yearly Total Volume Trends: Mann-Kendall Test Results'
#     SummerVol_title = 'Trend in Late Summer Volumes (08-01 through 09-30): Mann-Kendall Test Results'
#     FallVol_title = 'Trend in Fall to early Winter Volumes (10-01 through 12-31): Mann-Kendall Test Results'
#     WinterVol_title = 'Trend in Wintertime Volumes (01-01 through 4-01): Mann-Kendall Test Results'
#     RunoffVol_title = 'Trend in Runoff Season Volumes (04-01 through 07-31): Mann-Kendall Test Results'

Site 12301250 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 12302055 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 12304500 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 12306500 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 12324400 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 12324590 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 12332000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 12335100 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 12342500 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 12344000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 12359800 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 12370000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 12411000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 12413875 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 12414900 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 12415135 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 12442500 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 12448500 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 12451000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 12452990 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 12456500 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 13011900 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 13015000 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 13027500 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 13046995 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 13052200 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 13058000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 13063000 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 13073000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 13140335 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 13181000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 13185000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 13186000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 13235000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 13258500 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 13302005 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 13305310 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 13307000 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 13310700 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 13336500 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 13337000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 13338500 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 13340600 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 14038530 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 14044000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 14048000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 14087380 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 14091500 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 14093000 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 14097100 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 14101500 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 14139800 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 14159200 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 14161500 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 14178000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 14179000 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 14180300 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 14185000 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 14185900 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Number of included headwater sites: 37
Number of headwater sites excluded from study: 22
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.9223559101771723), z=np.float64(0.09746653335219396), Tau=np.float64(0.01019607843137255), s=np.float64(13.0), var_s=15158.333333333334, slope=np.float64(0.0006873548317398529), intercept=np.float64(0.6104561659374493))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.7575923297249587), z=np.float64(0.30864402228194754), Tau=np.float64(0.03058823529411765), s=np.float64(39.0), var_s=15158.333333333334, slope=np.float64(0.001829141858467376), intercept=np.float64(0.7248407831985545))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.6145585959057649), z=np.float64(0.5035770889863355), Tau=np.float64(0.04941176470588235), s=np.float64(63.0), var_s=15158.333333333334, slope=np.float64(0.0015122545804363986), intercept=np.float64(0.4119870239188421))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.25518981794772433), z=np.float64(1.1378339684970147), Tau=np.float64(0.11436170212765957), s=np.float64(129.0), var_s=np.float64(12655.0), slope=np.float64(0.0008649462539836879), intercept=np.float64(0.15133124696159453))

Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.8773518292022449), z=np.float64(-0.15432710172856248), Tau=np.float64(-0.01568627450980392), s=np.float64(-20.0), var_s=np.float64(15157.333333333334), slope=np.float64(-1.7709563164109075e-05), intercept=np.float64(0.07101206873934147))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.3138606891117792), z=np.float64(-1.007154177972671), Tau=np.float64(-0.09803921568627451), s=np.float64(-125.0), var_s=15158.333333333334, slope=np.float64(-0.0007769078343241002), intercept=np.float64(0.16127301725387844))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.9740822121735162), z=np.float64(-0.03248884445073132), Tau=np.float64(-0.00392156862745098), s=np.float64(-5.0), var_s=15158.333333333334, slope=np.float64(-0.00013301463836223228), intercept=np.float64(0.5672142548479447))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.6375777195034231), z=np.float64(-0.47108824453560416), Tau=np.float64(-0.04627450980392157), s=np.float64(-59.0), var_s=15158.333333333334, slope=np.float64(-0.0015096856005946918), intercept=np.float64(1.2265162446980626))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.7086857787122136), z=np.float64(0.3736217111834102), Tau=np.float64(0.03686274509803922), s=np.float64(47.0), var_s=15158.333333333334, slope=np.float64(0.0026365584216823884), intercept=np.float64(1.431423045885856))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.4549166374455147), z=np.float64(0.7472434223668204), Tau=np.float64(0.07294117647058823), s=np.float64(93.0), var_s=15158.333333333334, slope=np.float64(0.00404805632078357), intercept=np.float64(0.9603458830731565))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.10601362130595438), z=np.float64(1.6163733286307334), Tau=np.float64(0.1568627450980392), s=np.float64(200.0), var_s=np.float64(15157.333333333334), slope=np.float64(0.008359992890784677), intercept=np.float64(1.1618679463254244))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.5586827422707092), z=np.float64(0.5847992001131638), Tau=np.float64(0.05725490196078432), s=np.float64(73.0), var_s=15158.333333333334, slope=np.float64(0.002181433788199112), intercept=np.float64(0.871290601576014))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.39373678018444536), z=np.float64(0.8528602990262664), Tau=np.float64(0.08313725490196078), s=np.float64(106.0), var_s=np.float64(15157.333333333334), slope=np.float64(0.00026830808080807907), intercept=np.float64(0.23766787190082647))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.28730842597133455), z=np.float64(-1.0640447540232465), Tau=np.float64(-0.10352941176470588), s=np.float64(-132.0), var_s=np.float64(15157.333333333334), slope=np.float64(-0.0014950642791551865), intercept=np.float64(0.9546171946740127))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.3138606891117792), z=np.float64(-1.007154177972671), Tau=np.float64(-0.09803921568627451), s=np.float64(-125.0), var_s=15158.333333333334, slope=np.float64(-0.0008749107233955752), intercept=np.float64(0.49218957249260287))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='decreasing', h=np.True_, p=np.float64(0.0007987863402436624), z=np.float64(-3.353214989646512), Tau=np.float64(-0.3191919191919192), s=np.float64(-316.0), var_s=np.float64(8824.666666666666), slope=np.float64(-5.73921028466483e-06), intercept=np.float64(0.00012626262626262626))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='decreasing', h=np.True_, p=np.float64(1.798615595505204e-05), z=np.float64(-4.288527467496534), Tau=np.float64(-0.41490196078431374), s=np.float64(-529.0), var_s=15158.333333333334, slope=np.float64(-0.0037795308456465477), intercept=np.float64(0.41122380833124633))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='decreasing', h=np.True_, p=np.float64(0.014823473260879183), z=np.float64(-2.436663333804849), Tau=np.float64(-0.23607843137254902), s=np.float64(-301.0), var_s=15158.333333333334, slope=np.float64(-0.042140725436180006), intercept=np.float64(3.073398760330579))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.7330035595433548), z=np.float64(0.34113286673267884), Tau=np.float64(0.03372549019607843), s=np.float64(43.0), var_s=15158.333333333334, slope=np.float64(0.0016446936901482548), intercept=np.float64(1.3752738423192965))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.8074892496136439), z=np.float64(-0.2436663333804849), Tau=np.float64(-0.02431372549019608), s=np.float64(-31.0), var_s=15158.333333333334, slope=np.float64(-0.000465513723089481), intercept=np.float64(0.6407012039587797))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.7452655028453836), z=np.float64(0.3248884445073132), Tau=np.float64(0.03215686274509804), s=np.float64(41.0), var_s=15158.333333333334, slope=np.float64(0.0005785123966942164), intercept=np.float64(0.7473370064279157))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.5158363494239708), z=np.float64(-0.6497768890146264), Tau=np.float64(-0.06352941176470588), s=np.float64(-81.0), var_s=15158.333333333334, slope=np.float64(-0.005073461891643705), intercept=np.float64(1.813441230486685))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.3639241525837087), z=np.float64(0.9079130683127764), Tau=np.float64(0.09250693802035152), s=np.float64(100.0), var_s=np.float64(11890.0), slope=np.float64(0.002551270278543009), intercept=np.float64(0.40132996632996626))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.5370447511030623), z=np.float64(0.6172880445638951), Tau=np.float64(0.0603921568627451), s=np.float64(77.0), var_s=15158.333333333334, slope=np.float64(0.01245982552800735), intercept=np.float64(3.4911673553719007))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.820095683982129), z=np.float64(0.22742191115511923), Tau=np.float64(0.022745098039215685), s=np.float64(29.0), var_s=15158.333333333334, slope=np.float64(0.0032190592796653584), intercept=np.float64(2.9142893582287512))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.3982727995117967), z=np.float64(-0.8447099557190143), Tau=np.float64(-0.08235294117647059), s=np.float64(-105.0), var_s=15158.333333333334, slope=np.float64(-0.005628252219161315), intercept=np.float64(1.3200451484542397))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.7330035595433548), z=np.float64(0.34113286673267884), Tau=np.float64(0.03372549019607843), s=np.float64(43.0), var_s=15158.333333333334, slope=np.float64(0.008172635445362649), intercept=np.float64(4.508034894398532))

Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.18907223933881823), z=np.float64(-1.313328617757116), Tau=np.float64(-0.12897959183673469), s=np.float64(-158.0), var_s=np.float64(14290.666666666666), slope=np.float64(-0.0024840042655291956), intercept=np.float64(0.5028576453686425))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.3217296482185201), z=np.float64(-0.9909097557473052), Tau=np.float64(-0.09647058823529411), s=np.float64(-123.0), var_s=15158.333333333334, slope=np.float64(-0.0038405944971601582), intercept=np.float64(0.7285217494813456))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.15501875531212161), z=np.float64(-1.4220258205821483), Tau=np.float64(-0.13959183673469389), s=np.float64(-171.0), var_s=14291.666666666666, slope=np.float64(-0.05385483624119991), intercept=np.float64(7.149092248239977))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.9611318643887568), z=np.float64(-0.04873326667609698), Tau=np.float64(-0.005490196078431373), s=np.float64(-7.0), var_s=15158.333333333334, slope=np.float64(-0.0004890805286062473), intercept=np.float64(3.259242623867131))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.3310166880709866), z=np.float64(-0.9720680651424055), Tau=np.float64(-0.09898242368177614), s=np.float64(-107.0), var_s=11891.0, slope=np.float64(-0.00560773019450706), intercept=np.float64(1.2489272894231576))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.7173925102141454), z=np.float64(0.36194583115294365), Tau=np.float64(0.03838383838383838), s=np.float64(38.0), var_s=10450.0, slope=np.float64(0.0005469222135888823), intercept=np.float64(0.3577404385737719))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.4549166374455147), z=np.float64(-0.7472434223668204), Tau=np.float64(-0.07294117647058823), s=np.float64(-93.0), var_s=15158.333333333334, slope=np.float64(-0.0014416896235078136), intercept=np.float64(0.47217630853994513))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.9094669275616443), z=np.float64(-0.11371095557755961), Tau=np.float64(-0.011764705882352941), s=np.float64(-15.0), var_s=15158.333333333334, slope=np.float64(-0.0013924511573414153), intercept=np.float64(2.733066559006997))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.6727659347926815), z=np.float64(-0.42235497785950715), Tau=np.float64(-0.04156862745098039), s=np.float64(-53.0), var_s=15158.333333333334, slope=np.float64(-0.004524523307945773), intercept=np.float64(3.017474882514989))
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.5478109320607099), z=np.float64(-0.6010436223385294), Tau=np.float64(-0.058823529411764705), s=np.float64(-75.0), var_s=15158.333333333334, slope=np.float64(-0.006092954336755985), intercept=np.float64(2.43228253610485))
Site 07EA005 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 07EA007 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 07EE009 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 07FA005 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 07FB009 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 07FC001 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 07FC003 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08EC001 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 08EC013 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08EE003 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 08EE004 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08EE013 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08EG012 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08FB006 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08FB007 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 08FC003 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08GA071 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 08GA072 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 08HA001 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08JD006 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 08KA001 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08KA004 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08KA005 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08KA007 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08KB001 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08KD007 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 08KE016 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08LA001 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08LB020 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08LB038 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 08LB069 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08LD001 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08LE024 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08LG048 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08MA001 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08MA002 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08MB005 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08MB006 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08MG001 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 08MH001 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08MH016 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.

Site 08MH103 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08NA002 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08NB005 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08NB012 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08NB014 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08NC004 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08ND012 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08NE039 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08NH119 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08NH130 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08NK002 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08NK016 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08NK018 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08NL004 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08NN002 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 08NP001 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
Site 09AA006 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 10AC005 has more than 85% of data between 1968-10-01 and 2018-10-01 and will be included in the study.
Site 10CD004 is missing more than 15% of data between 1968-10-01 and 2018-10-01.  It will NOT be included in the study.
07EA005
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'
07EA007
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'
07EE009
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.5184436036506437), z=np.float64(0.6457464030007577), Tau=np.float64(0.06767676767676768), s=np.float64(67.0), var_s=np.float64(10446.333333333334), slope=np.float64(1.4323538414447509e-05), intercept=np.float64(0.002120901438628711))
07FA005
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'
07FB009
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'
07FC001
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.07662024926935085), z=np.float64(1.770642022564857), Tau=np.float64(0.17176470588235293), s=np.float64(219.0), var_s=15158.333333333334, slope=np.float64(2.600108225108225e-05), intercept=np.float64(0.0015423742293060472))
07FC003
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.9935192706405964), z=np.float64(-0.008122479038345393), Tau=np.float64(-0.001568627450980392), s=np.float64(-2.0), var_s=np.float64(15157.333333333334), slope=np.float64(-3.1565656565656274e-08), intercept=np.float64(0.00018207931588613412))
08EC001
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'
08EC013
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.9929079029266978), z=np.float64(0.008888742573342944), Tau=np.float64(0.0017730496453900709), s=np.float64(2.0), var_s=np.float64(12656.666666666666), slope=np.float64(1.5687174778084706e-06), intercept=np.float64(0.0430967439546985))
08EE003
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'
08EE004
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.3138606891117792), z=np.float64(1.007154177972671), Tau=np.float64(0.09803921568627451), s=np.float64(125.0), var_s=15158.333333333334, slope=np.float64(0.00019480519480519448), intercept=np.float64(0.05429883248065066))
08EE013
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.5149628470431733), z=np.float64(0.6511295742445165), Tau=np.float64(0.0666049953746531), s=np.float64(72.0), var_s=np.float64(11890.0), slope=np.float64(4.225589225589226e-06), intercept=np.float64(0.0008647030915212734))
08EG012
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.298505781092252), z=np.float64(1.0396430224234023), Tau=np.float64(0.1011764705882353), s=np.float64(129.0), var_s=15158.333333333334, slope=np.float64(0.0001391241965105601), intercept=np.float64(0.017829287190082647))
08FB006
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.3936951670173994), z=np.float64(0.8529353318244607), Tau=np.float64(0.08313725490196078), s=np.float64(106.0), var_s=np.float64(15154.666666666666), slope=np.float64(7.852879443788535e-05), intercept=np.float64(0.01451520070838253))
08FB007
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'
08FC003
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.1853974504493967), z=np.float64(1.3243180135333934), Tau=np.float64(0.13297872340425532), s=np.float64(150.0), var_s=12658.666666666666, slope=np.float64(5.045207317934604e-05), intercept=np.float64(0.007508820724729814))
08GA071
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'
08GA072
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'
08HA001
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.3138606891117792), z=np.float64(1.007154177972671), Tau=np.float64(0.09803921568627451), s=np.float64(125.0), var_s=15158.333333333334, slope=np.float64(0.00023681747545383896), intercept=np.float64(0.05775380553789645))
08JD006
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'
08KA001
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.6492216008659899), z=np.float64(0.45484382231023845), Tau=np.float64(0.04470588235294118), s=np.float64(57.0), var_s=15158.333333333334, slope=np.float64(2.2435094749143764e-06), intercept=np.float64(0.0033334898572501886))
08KA004
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.24216262143915523), z=np.float64(1.1695984002263276), Tau=np.float64(0.11372549019607843), s=np.float64(145.0), var_s=15158.333333333334, slope=np.float64(0.0004909769633089777), intercept=np.float64(0.17730087435621034))

08KA005
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.4451725088539811), z=np.float64(0.763487844592186), Tau=np.float64(0.07450980392156863), s=np.float64(95.0), var_s=15158.333333333334, slope=np.float64(8.302724211815132e-05), intercept=np.float64(0.06135636669727578))
08KA007
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.5424012067003148), z=np.float64(0.6091859278759045), Tau=np.float64(0.0596078431372549), s=np.float64(76.0), var_s=np.float64(15157.333333333334), slope=np.float64(1.1407784135056904e-05), intercept=np.float64(0.012045383909020272))
08KB001
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.6145585959057649), z=np.float64(0.5035770889863355), Tau=np.float64(0.04941176470588235), s=np.float64(63.0), var_s=15158.333333333334, slope=np.float64(0.0005174216916641159), intercept=np.float64(0.37188998571574333))
08KD007
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'
08KE016
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.5263859860736959), z=np.float64(0.6335324667892608), Tau=np.float64(0.06196078431372549), s=np.float64(79.0), var_s=15158.333333333334, slope=np.float64(8.133708627779787e-06), intercept=np.float64(0.0024007895157104643))
08LA001
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.37161986490091525), z=np.float64(0.8934432223951113), Tau=np.float64(0.08705882352941176), s=np.float64(111.0), var_s=15158.333333333334, slope=np.float64(0.00019427226813590465), intercept=np.float64(0.08130480945821855))
08LB020
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.6846613702155371), z=np.float64(0.4061105556341415), Tau=np.float64(0.04), s=np.float64(51.0), var_s=15158.333333333334, slope=np.float64(1.1089920180829266e-05), intercept=np.float64(0.006243413152504062))
08LB038
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'
08LB069
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.48485820892479525), z=np.float64(0.6985101556907234), Tau=np.float64(0.06823529411764706), s=np.float64(87.0), var_s=15158.333333333334, slope=np.float64(9.400826446280997e-06), intercept=np.float64(0.0040815541781450875))
08LD001
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.8278293809763932), z=np.float64(0.2174863019713874), Tau=np.float64(0.022040816326530613), s=np.float64(27.0), var_s=14291.666666666666, slope=np.float64(1.3774104683195923e-05), intercept=np.float64(0.03836547291092745))
08LE024
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.820095683982129), z=np.float64(0.22742191115511923), Tau=np.float64(0.022745098039215685), s=np.float64(29.0), var_s=15158.333333333334, slope=np.float64(1.8119506755870126e-05), intercept=np.float64(0.021074330972058252))
08LG048
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.14824633079901028), z=np.float64(1.4457535780575437), Tau=np.float64(0.1403921568627451), s=np.float64(179.0), var_s=15158.333333333334, slope=np.float64(2.8467274627149215e-05), intercept=np.float64(0.0035357928817960176))
08MA001
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.7330035595433548), z=np.float64(-0.34113286673267884), Tau=np.float64(-0.03372549019607843), s=np.float64(-43.0), var_s=15158.333333333334, slope=np.float64(-4.124315252841849e-05), intercept=np.float64(0.03770233684810486))
08MA002
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.8581821860709902), z=np.float64(0.17868864447902225), Tau=np.float64(0.01803921568627451), s=np.float64(23.0), var_s=15158.333333333334, slope=np.float64(1.3716712580348449e-05), intercept=np.float64(0.02140777089072545))
08MB005
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.22421478196718714), z=np.float64(-1.215396815635578), Tau=np.float64(-0.12074829931972789), s=np.float64(-142.0), var_s=13458.666666666666, slope=np.float64(-0.00015140754132231368), intercept=np.float64(0.05782570018365472))
08MB006
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='increasing', h=np.True_, p=np.float64(0.03811478410347702), z=np.float64(2.073618194190298), Tau=np.float64(0.21256038647342995), s=np.float64(220.0), var_s=np.float64(11154.0), slope=np.float64(1.6326140189776538e-05), intercept=np.float64(0.0010734446740128564))
08MG001
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'
08MH001
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.27284485950275017), z=np.float64(1.096534670176628), Tau=np.float64(0.10666666666666667), s=np.float64(136.0), var_s=np.float64(15157.333333333334), slope=np.float64(0.00045372556736192934), intercept=np.float64(0.10002967991604357))
08MH016
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.3217296482185201), z=np.float64(0.9909097557473052), Tau=np.float64(0.09647058823529411), s=np.float64(123.0), var_s=15158.333333333334, slope=np.float64(9.817025473591142e-05), intercept=np.float64(0.023805844641703225))
08MH103
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.13504841780667975), z=np.float64(1.4944868447336408), Tau=np.float64(0.1450980392156863), s=np.float64(185.0), var_s=15158.333333333334, slope=np.float64(0.00023301193755739225), intercept=np.float64(0.04563934802571166))
08NA002
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.8901754978848897), z=np.float64(0.13808214365187169), Tau=np.float64(0.01411764705882353), s=np.float64(18.0), var_s=np.float64(15157.333333333334), slope=np.float64(1.4252372206917675e-05), intercept=np.float64(0.05129199188858279))
08NB005
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.12277737926108978), z=np.float64(1.5432201114097377), Tau=np.float64(0.14980392156862746), s=np.float64(191.0), var_s=15158.333333333334, slope=np.float64(0.0001720041322314042), intercept=np.float64(0.06547262396694216))
08NB012
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.3746251747453009), z=np.float64(0.8878430639040038), Tau=np.float64(0.08843537414965986), s=np.float64(104.0), var_s=13458.666666666666, slope=np.float64(8.709119163664627e-06), intercept=np.float64(0.004531568835205199))
08NB014
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='increasing', h=np.True_, p=np.float64(0.01023677508574461), z=np.float64(2.567726964527109), Tau=np.float64(0.2599444958371878), s=np.float64(281.0), var_s=11891.0, slope=np.float64(2.1694214876033036e-05), intercept=np.float64(0.0033910697887970616))

08NC004
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.5178287639890917), z=np.float64(0.6466959203388403), Tau=np.float64(0.06462585034013606), s=np.float64(76.0), var_s=np.float64(13450.0), slope=np.float64(4.05700121609214e-06), intercept=np.float64(0.0033888578661305934))
08ND012
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.1828461830167143), z=np.float64(1.3320426224799842), Tau=np.float64(0.12941176470588237), s=np.float64(165.0), var_s=15158.333333333334, slope=np.float64(3.558310376492206e-05), intercept=np.float64(0.012652203856749304))
08NE039
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.8327487758796983), z=np.float64(0.21117748892975358), Tau=np.float64(0.021176470588235293), s=np.float64(27.0), var_s=15158.333333333334, slope=np.float64(9.187837975716795e-06), intercept=np.float64(0.003141837567595142))
08NH119
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.24216262143915523), z=np.float64(1.1695984002263276), Tau=np.float64(0.11372549019607843), s=np.float64(145.0), var_s=15158.333333333334, slope=np.float64(3.9170110192837615e-05), intercept=np.float64(0.017494117309458213))
08NH130
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='increasing', h=np.True_, p=np.float64(0.019358011655962182), z=np.float64(2.3385639638359392), Tau=np.float64(0.23681776133209992), s=np.float64(256.0), var_s=np.float64(11890.0), slope=np.float64(3.2511259783987095e-05), intercept=np.float64(0.004496960951506405))
08NK002
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.45154775008090664), z=np.float64(0.7528371991317256), Tau=np.float64(0.07428571428571429), s=np.float64(91.0), var_s=14291.666666666666, slope=np.float64(5.66804407713499e-05), intercept=np.float64(0.027424575298438933))
08NK016
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.8581821860709902), z=np.float64(0.17868864447902225), Tau=np.float64(0.01803921568627451), s=np.float64(23.0), var_s=15158.333333333334, slope=np.float64(4.553106825833936e-06), intercept=np.float64(0.011712389041934501))
08NK018
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='increasing', h=np.True_, p=np.float64(0.005773008752393283), z=np.float64(2.760403063482994), Tau=np.float64(0.2702040816326531), s=np.float64(331.0), var_s=14291.666666666666, slope=np.float64(2.3264798763690105e-05), intercept=np.float64(0.0036885064615108966))
08NL004
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.3544812853097272), z=np.float64(0.9259320668458426), Tau=np.float64(0.09019607843137255), s=np.float64(115.0), var_s=15158.333333333334, slope=np.float64(7.093663911845744e-06), intercept=np.float64(0.002554292929292929))
08NN002
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.4549166374455147), z=np.float64(0.7472434223668204), Tau=np.float64(0.07294117647058823), s=np.float64(93.0), var_s=15158.333333333334, slope=np.float64(7.703659976387256e-05), intercept=np.float64(0.012470779220779217))
08NP001
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'
09AA006
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.23555044635596767), z=np.float64(-1.1861819663838258), Tau=np.float64(-0.11529411764705882), s=np.float64(-147.0), var_s=np.float64(15149.666666666666), slope=np.float64(-0.0001320018365472908), intercept=np.float64(0.0930084940312213))
10AC005
Mann-Kendall Test Results looking for trend in discharge from 01-01 to 03-31: Mann_Kendall_Test(trend='no trend', h=np.False_, p=np.float64(0.19375395039491927), z=np.float64(1.2995537780292528), Tau=np.float64(0.12627450980392158), s=np.float64(161.0), var_s=15158.333333333334, slope=np.float64(1.651617181920203e-05), intercept=np.float64(0.005537968064483218))
10CD004
Invalid input type. Please provide either a pandas DataFrame or a CSV file path.
Saving to volume_stats_ca prob failed
'DataLoader' object has no attribute '_df'

NameError: name 'modified_flows_m' is not defined

In [ ]:
file_name = 'USGS_individual_sites.html'
if os.path.exists(file_name):
    os.remove(file_name)
for fig in figs_hw:
    with open(file_name, 'a') as f:
        f.write(fig.fig.to_html(full_html=False, include_plotlyjs='cdn', default_width=1200, default_height=400))

file_name = 'EnvCan_individual_sites.html'
if os.path.exists(file_name):
    os.remove(file_name)
for fig in figs_ca:
    with open(file_name, 'a') as f:
        f.write(fig.fig.to_html(full_html=False, include_plotlyjs='cdn', default_width=1200, default_height=400))

file_name = 'MF_individual_sites.html'
if os.path.exists(file_name):
    os.remove(file_name)
for fig in figs_mf:
    with open(file_name, 'a') as f:
        f.write(fig.fig.to_html(full_html=False, include_plotlyjs='cdn', default_width=1200, default_height=400))

In [28]:
volume_stats_df
trend = volume_stats_df['Jan'].apply(lambda x: x[0]).to_list()
p_val = volume_stats_df['Jan'].apply(lambda x: x[2]).to_list()
tau = volume_stats_df['Jan'].apply(lambda x: x[3]).to_list()

In [29]:
p_val

[0.3769975791490947,
 0.4929963604314964,
 0.9943609699435021,
 0.3572678429123073,
 0.33642307585176723,
 0.3087965659991987,
 0.07151057805609917,
 0.1183056066542365,
 0.26717014502974124,
 0.6459542929981457,
 0.008558886421878409,
 0.8046267471952453,
 0.32242854483688665,
 0.07151057805609917,
 0.01117287192680294,
 1.0889247175072114e-06,
 2.087904471537172e-08,
 0.003063462337335121,
 0.06306092548724385,
 0.02897192753396549,
 0.08590410553587513,
 0.09393309804459693,
 0.14646717796371345,
 0.7079733321543815,
 0.4163519362835637,
 0.03707630837435305,
 0.18162639007607662,
 0.016919535563399535,
 0.0025458545171921365,
 0.001144856164775554,
 0.21095137661039587,
 0.1983574171428546,
 0.9733082170178828,
 0.15959367256834933,
 0.22683636265300655,
 0.15959367256834933,
 0.23788953280067782,
 0.13812390972107313,
 0.11664049661843734,
 0.7936642234391675,
 0.7884645974487259,
 0.904365834981387,
 0.19560435481130378,
 0.11351728455021748,
 0.2669709555047193,
 0.028804611096681976,
 0.0035127798731711124,
 0.4678669654464569,
 0.015945206468415796,
 0.14253196863002504,
 0.34002431290207236,
 0.9943609699435021,
 0.24542788785456393,
 0.025355809999107137,
 0.3694111397746025,
 0.28263809663209316,
 0.3627333820663041,
 0.12379880381145236,
 0.45460955873641584,
 0.5863037215101836,
 0.4929963604314964,
 0.8278293809763932,
 0.0033229451869876137,
 0.08018817752581575,
 0.0885164452069922,
 0.04357541843759338,
 0.6818593049042891,
 0.21615443061948447,
 0.8813894797360706,
 0.034705762068839574,
 0.8112680715255163,
 0.006067591381943682,
 0.7604417950782034,
 0.18629171120511856,
 0.2268222890669649,
 0.6422103646774804,
 0.008266605644713598,
 0.1025530316567056,
 0.24931770656346863,
 0.18619639324069315,
 0.07650621027113003]

In [7]:
volume_stats_df = pd.DataFrame(volume_stats).T

NameError: name 'volume_stats' is not defined

In [21]:
vol_stats_df_long = pd.melt(volume_stats_df, id_vars[])

SyntaxError: invalid syntax (3897298833.py, line 1)

In [10]:
vol_stats_df_long

NameError: name 'vol_stats_df_long' is not defined

In [11]:
volume_stats_df2 = volume_stats_df

In [12]:
volume_stats_df3 = volume_stats_df

In [19]:
volume_stats_df = volume_stats_df2

In [13]:
# months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
# results = {}
# volume_stats_df = volume_stats_df.reset_index()
# volume_stats_df = volume_stats_df.rename(columns={'index':'Site'})
# for month in months: 
#     volume_stats_df[[f'{month}_trend', f'{month}_h', f'{month}_p', f'{month}_z', 
#                      f'{month}_tau', f'{month}_s', f'{month}_var_s', f'{month}_slope',
#                      f'{month}_intercept']] = pd.DataFrame(volume_stats_df[month].tolist(), index=volume_stats_df.index)

# volume_stats_df = volume_stats_df.drop(columns=months)

# volume_stats_df_long = pd.melt(volume_stats_df, id_vars=['Site'],
#                               value_vars=[col for col in volume_stats_df.columns if 'trend' or 'p_value' or 'tau_value'],
#                                var_name='Month_Metric', value_name='Value')

# # volume_stats_df_long[['Month', 'Metric']] = volume_stats_df_long['Month_Metric'].str.split('_', expand=True)
# # volume_stats_df_long.drop(columns=['Month_Metric'])

In [84]:
volume_stats_df.columns

Index(['Site', 'lat', 'long', 'name', 'Site Type', 'Jan_trend', 'Jan_h',
       'Jan_p', 'Jan_z', 'Jan_tau',
       ...
       'Nov_intercept', 'Dec_trend', 'Dec_h', 'Dec_p', 'Dec_z', 'Dec_tau',
       'Dec_s', 'Dec_var_s', 'Dec_slope', 'Dec_intercept'],
      dtype='object', length=113)

In [14]:
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
results = {}
for month in months:   
    for site in volume_stats_df.index:
        results[f'{month}_trend'] = volume_stats_df[month].loc[site][0]
        results[f'{month}_p'] = volume_stats_df[month].loc[site][2]
        results[f'{month}_z'] = volume_stats_df[month].loc[site][3]
        results[f'{month}_tau'] = volume_stats_df[month].loc[site][4]
        results[f'{month}_s'] = volume_stats_df[month].loc[site][5]
        results[f'{month}_var_s'] = volume_stats_df[month].loc[site][6]
        results[f'{month}_slope'] = volume_stats_df[month].loc[site][7]

In [30]:
# results

In [ ]:
# peak_runoffQ = pd.DataFrame({'sites':sites, 'site_name': site_name, 'site_type': site_type, 'lat': lat, 'long': long, 'trend': PeakRunoffQ_trend,  'p': PeakRunoffQ_p, 'tau': PeakRunoffQ_tau})
# peak_runoffDOY = pd.DataFrame({'sites':sites, 'site_name': site_name, 'site_type': site_type,'lat': lat, 'long': long, 'trend': PeakRunoffDOY_trend,  'p': PeakRunoffDOY_p, 'tau': PeakRunoffDOY_tau})
# ThresholdVol = pd.DataFrame({'sites':sites, 'site_name': site_name, 'site_type': site_type,'lat': lat, 'long': long, 'trend': ThresholdVol_trend, 'p': ThresholdVol_p, 'tau': ThresholdVol_tau})
# ThresholdDOY = pd.DataFrame({'sites':sites, 'site_name': site_name, 'site_type': site_type,'lat': lat, 'long': long, 'trend': ThresholdDOY_trend, 'p': ThresholdDOY_p, 'tau': ThresholdDOY_tau})
# total_vol = pd.DataFrame({'sites':sites, 'site_name': site_name, 'site_type': site_type,'lat': lat, 'long': long, 'trend': TotalVol_trend, 'p': TotalVol_p, 'tau': TotalVol_tau})
# RunoffVol = pd.DataFrame({'sites':sites, 'site_name': site_name, 'site_type': site_type,'lat': lat, 'long': long, 'trend': RunoffVol_trend, 'p': RunoffVol_p, 'tau': RunoffVol_tau})
# SummerVol = pd.DataFrame({'sites':sites, 'site_name': site_name, 'site_type': site_type,'site_type': site_type,'lat': lat, 'long': long, 'trend': SummerVol_trend, 'p': SummerVol_p, 'tau': SummerVol_tau})
# WinterVol = pd.DataFrame({'sites':sites, 'site_name': site_name, 'site_type': site_type,'lat': lat, 'long': long, 'trend': WinterVol_trend, 'p': WinterVol_p, 'tau': WinterVol_tau})
# FallVol = pd.DataFrame({'sites':sites, 'site_name': site_name, 'site_type': site_type, 'lat': lat, 'long': long, 'trend': FallVol_trend, 'p': FallVol_p, 'tau': FallVol_tau})

In [25]:
# volume_stats_df#.loc[:,['Jun', 'Jul']]

In [26]:
# volume_stats_df.loc[:,'Jan'].iloc[0]

In [24]:
# meta_df = volume_stats_df.loc[:, ['lat', 'long', 'name']]
# meta_df

In [23]:
# month_stats = volume_stats_df.loc[:, month]
# month_stats.to_list()

In [22]:
# df =volume_stats_df.drop(month, axis=1)
# df

In [20]:
# volume_stats_df4 = volume_stats_df.reset_index()
# volume_stats_df4 = volume_stats_df4.rename(columns={'index':'site_id'})

In [21]:
# meta_df = volume_stats_df.loc[:, ['lat', 'long', 'name', 'Site Type']]
# meta_df

In [16]:
meta_df = volume_stats_df.loc[:, ['lat', 'long', 'name', 'Site Type']]
stats = pd.DataFrame(month_stats.to_list(), columns=['trend', 'h', 'p', 'z', 'Tau', 's', 'var_s', 'slope', 'intercept'])
#     print(stats)
stats = pd.merge(meta_df, stats, left_index=True, right_index=True)
#     stats = pd.concat([volume_stats_df.drop(month, axis=1), stats], axis=1)
#     stats = pd.concat([meta_df, stats], axis=1)

In [17]:
volume_stats_df

,site_id,lat,long,name,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Site Type
0,12302055,48.355603,-115.31465,Fisher River near Libby MT,"(no trend, False, 0.3769975791490947, -0.88344...","(no trend, False, 0.16383024552965075, -1.3923...","(no trend, False, 0.6257907526390425, -0.48765...","(decreasing, True, 0.04252122229706323, -2.028...","(decreasing, True, 0.03458425704938328, -2.113...","(decreasing, True, 0.02897192753396549, -2.183...","(decreasing, True, 0.014189316241066674, -2.45...","(no trend, False, 0.11501190973233788, -1.5760...","(decreasing, True, 0.00016522357012860311, -3....","(decreasing, True, 0.022441339818437545, -2.28...","(no trend, False, 0.893178666143057, 0.1342831...","(no trend, False, 0.5201295773063765, -0.64314...",USGS
1,12304500,48.561722,-115.970158,Yaak River near Troy MT,"(no trend, False, 0.4929963604314964, -0.68555...","(no trend, False, 0.26717014502974124, -1.1096...","(no trend, False, 0.8155838577068915, -0.23322...","(decreasing, True, 0.03581179937943069, -2.099...","(decreasing, True, 0.02328787110405961, -2.268...","(no trend, False, 0.11179077639088408, -1.5901...","(decreasing, True, 0.009890042498012619, -2.57...","(no trend, False, 0.12511453035353104, -1.5336...","(decreasing, True, 0.00020688638717691887, -3....","(decreasing, True, 0.025064410296220307, -2.24...","(no trend, False, 0.44108559892650057, -0.7703...","(no trend, False, 0.3924560862377737, -0.85517...",USGS
2,12306500,48.999167,-116.179722,MOYIE RIVER AT EASTPORT ID,"(no trend, False, 0.9943609699435021, 0.007067...","(no trend, False, 0.5574687558262528, -0.58660...","(no trend, False, 0.9718104820638074, 0.035337...","(no trend, False, 0.13222513880168085, -1.5053...","(no trend, False, 0.07151057805609917, -1.8022...","(no trend, False, 0.19104500437867866, -1.3074...","(no trend, False, 0.053676629729880077, -1.929...","(no trend, False, 0.5386369182940962, -0.61487...","(decreasing, True, 0.0005482053288650146, -3.4...","(decreasing, True, 0.04398355971361223, -2.014...","(no trend, False, 0.7937078807228737, -0.26149...","(no trend, False, 0.893178666143057, 0.1342831...",USGS
3,12324590,46.519483,-112.793172,Little Blackfoot River near Garrison MT ST,"(no trend, False, 0.3572678429123073, 0.920583...","(no trend, False, 0.5495868272974844, 0.598379...","(no trend, False, 0.48032446614667323, 0.70578...","(no trend, False, 0.932756112362773, 0.0843777...","(no trend, False, 0.7241913677645959, -0.35286...","(no trend, False, 0.878068201766014, 0.1534185...","(no trend, False, 0.5807381377006675, 0.552306...","(no trend, False, 0.6956450897588282, 0.391205...","(no trend, False, 0.12311946423625697, -1.5418...","(no trend, False, 0.3493487373444992, 0.935853...","(no trend, False, 0.0751095077140096, 1.779795...","(no trend, False, 0.05320840506825131, 1.93322...",USGS
4,12332000,46.184569,-113.501569,Middle Fork Rock Cr nr Philipsburg MT ST,"(no trend, False, 0.33642307585176723, 0.96125...","(no trend, False, 0.7665857025635621, -0.29684...","(no trend, False, 0.6922585963374686, 0.395791...","(no trend, False, 0.7291103467049747, -0.34630...","(no trend, False, 0.26112416790502824, 1.12373...","(no trend, False, 0.16383024552965075, -1.3923...","(no trend, False, 0.13589590503090587, -1.4912...","(no trend, False, 0.4666404614778705, -0.72795...","(no trend, False, 0.2551734655146509, -1.13787...","(no trend, False, 0.6257907526390425, -0.48765...","(no trend, False, 0.6510287224403535, 0.452333...","(no trend, False, 0.24069953548696743, 1.17324...",USGS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,08NK018,"53 49.893959 Name: LATITUDE, dtype: float64","53 -114.866661 Name: LONGITUDE, dtype: float64",53 FORDING RIVER AT THE MOUTH Name: STATION...,"(increasing, True, 0.008266605644713598, 2.640...","(increasing, True, 0.016971316038902007, 2.387...","(increasing, True, 0.008637922901820527, 2.626...","(no trend, False, 0.4118489667343037, -0.82064...","(no trend, False, 0.11373973214427902, -1.5816...","(no trend, False, 0.23850033694372996, -1.1787...","(no trend, False, 0.6119392033141589, -0.50730...","(no trend, False, 0.9524079410989388, 0.059683...","(no trend, False, 0.3549191885808012, -0.92508...","(no trend, False, 0.31745869581880415, 0.99969...","(increasing, True, 0.003980346998691875, 2.879...","(increasing, True, 0.01564170257684716, 2.4171...",Environmental Canada
77,08NL004,"54 49.20763 Name: LATITUDE, dtype: float64","54 -119.993523 Name: LONGITUDE, dtype: float64",54 ASHNOLA RIVER NEAR KEREMEOS Name: STATIO...,"(no trend, False, 0.1025530316567056, 1.632600...","(no trend, False, 0.2795490826171796, 1.081332...","(no trend, False, 0.1554404901436115, 1.420574...","(no trend, False, 0.6561357004326704, 0.445254...","(no trend, False, 0.09961239563208757, 1.64673...","(no trend, False, 0.19588696094503932, -1.2933...","(no trend, False, 0.27331169511606057, -1.0954...","(no trend, False, 0.882012711198483, -0.148418...","(no trend, False, 0.23788953280067782, -1.1802...","(no trend, False, 0.44108559892650057, 0.77036...","(increasing, True, 0.02162168773259565, 2.2969...","(no trend, False, 0.2214492453505552, 1.222683...",Environmental Canada
78,08NN002,"55 49.04327 Name: LATITUDE, dtype: float64","55 -118.44043 Name: LONGITUDE, dtype: float64",55 GRANBY RIVER AT GRAND FORKS Name: STATIO...,"(no trend, False, 0.24931770656346863, 1.15200...","(no trend, False, 0.596066781873303, 0.5300651...","(no trend, False, 0.7079733321543815, 0.374579...","(no trend, False, 0.4929963604314964, -0.68555...","(no trend, False, 0.38467934665968073, -0.8693...","(no trend, False, 0.26112416790502824, -1.1237...","(no trend, False, 0.13222513880168085, -1.5053...","(no trend, False, 0.11179077639088408, -1.5901...","(decreasing, True, 0.0026671612554125534, -3.0...","(decreasing, True, 0.025995867237205594, -2.22...","(no trend, False, 0.5019556708124682, -0.67141...","(no trend, False, 0.6459542929981457, 0.459389...",Environmental Canada
79,09AA006,"57 59.59536 Name: LATITUDE, dtype: float64","57 -133.814423 Name: LONGITUDE, dtype: float64",57 ATLIN RIVER NEAR ATLIN Name: STATION_NAM...,"(no trend, False, 0.18619639324069315, -1.3219...","(no trend, False, 0.3053563680924174, -1.02501...","(no trend, False, 0.6974251471625419, -0.38879...","(increasing, True, 0.0010668813922112275, 3.27...","(no trend, False, 0.06406310986478059, 1.85174...","(increasing, True, 0.004595760873002952, 2.834...","(increasing, True, 0.0006085956890595767, 3.42...","(increasing, True, 0.0010147544946887965, 3.28...","(increasing, True, 0.0004680062933652973, 3.49...","(no trend, False, 0.07963764154935515, 1.75279...","(no trend, False, 0.949282509396226, -0.063607...","(no trend, False, 0.27331169511606057, -1.0954...",Environmental Canada
80,10AC005,"58 59.1175 Name: LATITUDE, dtype: float64","58 -129.825546 Name: LONGITUDE, dtype: float64",58 COTTONWOOD RIVER ABOVE BASS CREEK Name: ...,"(no trend, False, 0.07650621027113003, 1.77132...","(no trend, False, 0.17231795094810276, 1.36479...","(no trend, False, 0.37579867194936134, 0.88566...","(no trend, False, 0.9190475393772803, -0.10163...","(increasing, True, 0.03854388668520392, 2.0690...","(no trend, False, 0.28263809663209316, -1.0744...","(no trend, False, 0.11351728455021748, -1.5825...","(no trend, False, 0.28263809663209316, -1.0744...","(no trend, False, 0.6950470090074785, -0.39201...","(no trend, False, 0.5516547939501897, -0.59528...","(no trend, False, 0.8050441548221507, -0.24682...","(no trend, False, 0.33793202583225646, 0.95825...",Environmental Canada

In [19]:
for month in months:
    volume_stats_df = volume_stats_df3
    volume_stats_df = volume_stats_df.reset_index()
    volume_stats_df = volume_stats_df.rename(columns={'index':'site_id'})
    month_stats = volume_stats_df.loc[:, month]
    meta_df = volume_stats_df.loc[:, ['site_id', 'lat', 'long', 'name', 'Site Type']]
    del stats
    stats = pd.DataFrame(month_stats.to_list(), columns=['trend', 'h', 'p', 'z', 'Tau', 's', 'var_s', 'slope', 'intercept'])
#     print(stats)
    stats = pd.merge(meta_df, stats, left_index=True, right_index=True)
#     stats = pd.concat([volume_stats_df.drop(month, axis=1), stats], axis=1)
#     stats = pd.concat([meta_df, stats], axis=1)

#     print(stats)
    
    
    color_scale_decr = [
        [0.0, 'rgb(165,0,38)'],
        [0.05, 'rgb(215, 48, 39)'],
        [0.1, 'rgb(244,109,67)'],
        [0.15, 'rgb(253,174,97)'],
#             [.2, 'rgb(254,224,144)'],
        [.1501, 'rgb(128,128,128)'],
        [1.0, 'rgb(128,128,128)']
    ]

    color_scale_incr = [
        [0.0, 'rgb(0, 109, 44)'],
        [0.05, 'rgb(49, 163, 84)'],
        [0.1, 'rgb(116, 196, 118)'],
        [0.15, 'rgb(186, 228, 179)'],
#             [.2, 'rgb(237,248,233)'],
        [.1501, 'rgb(128,128,128)'],
        [1.0, 'rgb(128,128,128)']
    ]

    # Create bins for p values
    bins = np.linspace(0, 1, num=len(color_scale_decr))

    def get_color_decr(p):
        for i in range(len(bins) - 1):
            if bins[i] <= p < bins[i + 1]:
                return color_scale_decr[i][1]
        return color_scale_decr[-1][1]

    def get_color_incr(p):
        for i in range(len(bins) - 1):
            if bins[i] <= p < bins[i + 1]:
                return color_scale_incr[i][1]
        return color_scale_incr[-1][1]
    
    stats['trend_color1'] = stats[stats['Tau']<0]['p'].apply(get_color_decr)
    stats['trend_color2'] = stats[stats['Tau']>=0]['p'].apply(get_color_incr)
    stats['trend_color'] = stats['trend_color1'].combine_first(stats['trend_color2'])

    stats['confidence_level'] = (1 - stats['p'])*100

    stats_hw = stats[stats['Site Type']=='USGS']
    stats_hw_pos_tau = stats_hw[stats_hw["Tau"]>0]
    stats_hw_neg_tau = stats_hw[stats_hw["Tau"]<=0]

    stats_mf = stats[stats['Site Type']=='modified flows']
    stats_mf_pos_tau = stats_mf[stats_mf["Tau"]>0]
    stats_mf_neg_tau = stats_mf[stats_mf["Tau"]<=0]

    stats_ca = stats[stats['Site Type']=='Environmental Canada']
    stats_ca_pos_tau = stats_ca[stats_ca["Tau"]>0]
    stats_ca_neg_tau = stats_ca[stats_ca["Tau"]<=0]

    
    traces = []

In [ ]:
figs = []
small_circle = 8
large_circle = 13
#      dates_ranges = {'01-01':'04-01', '04-01':'07-31', '08-01':'09-30', '10-01':'12-31'} 
for month in months:
    volume_stats_df = volume_stats_df3
    volume_stats_df = volume_stats_df.reset_index()
    volume_stats_df = volume_stats_df.rename(columns={'index':'site_id'})
    month_stats = volume_stats_df.loc[:, month]
    meta_df = volume_stats_df.loc[:, ['site_id', 'lat', 'long', 'name', 'Site Type']]
    del stats
    stats = pd.DataFrame(month_stats.to_list(), columns=['trend', 'h', 'p', 'z', 'Tau', 's', 'var_s', 'slope', 'intercept'])
#     print(stats)
    stats = pd.merge(meta_df, stats, left_index=True, right_index=True)
    
    
    color_scale_decr = [
        [0.0, 'rgb(165,0,38)'],
        [0.05, 'rgb(215, 48, 39)'],
        [0.1, 'rgb(244,109,67)'],
        [0.15, 'rgb(253,174,97)'],
#             [.2, 'rgb(254,224,144)'],
        [.1501, 'rgb(128,128,128)'],
        [1.0, 'rgb(128,128,128)']
    ]

    color_scale_incr = [
        [0.0, 'rgb(0, 109, 44)'],
        [0.05, 'rgb(49, 163, 84)'],
        [0.1, 'rgb(116, 196, 118)'],
        [0.15, 'rgb(186, 228, 179)'],
#             [.2, 'rgb(237,248,233)'],
        [.1501, 'rgb(128,128,128)'],
        [1.0, 'rgb(128,128,128)']
    ]

    # Create bins for p values
    bins = np.linspace(0, 1, num=len(color_scale_decr))

    def get_color_decr(p):
        for i in range(len(bins) - 1):
            if bins[i] <= p < bins[i + 1]:
                return color_scale_decr[i][1]
        return color_scale_decr[-1][1]

    def get_color_incr(p):
        for i in range(len(bins) - 1):
            if bins[i] <= p < bins[i + 1]:
                return color_scale_incr[i][1]
        return color_scale_incr[-1][1]
    
    stats['trend_color1'] = stats[stats['Tau']<0]['p'].apply(get_color_decr)
    stats['trend_color2'] = stats[stats['Tau']>=0]['p'].apply(get_color_incr)
    stats['trend_color'] = stats['trend_color1'].combine_first(stats['trend_color2'])

    stats['confidence_level'] = (1 - stats['p'])*100

    stats_hw = stats[stats['Site Type']=='USGS']
    stats_hw_pos_tau = stats_hw[stats_hw["Tau"]>0]
    stats_hw_neg_tau = stats_hw[stats_hw["Tau"]<=0]

    stats_mf = stats[stats['Site Type']=='modified flows']
    stats_mf_pos_tau = stats_mf[stats_mf["Tau"]>0]
    stats_mf_neg_tau = stats_mf[stats_mf["Tau"]<=0]

    stats_ca = stats[stats['Site Type']=='Environmental Canada']
    stats_ca_pos_tau = stats_ca[stats_ca["Tau"]>0]
    stats_ca_neg_tau = stats_ca[stats_ca["Tau"]<=0]
    
    traces = []


    # decreasing------------------------------------
    title=f'{month} - Trends in Volume'
    trace = go.Scattermapbox(
            mode='markers',
            lon = stats_hw_neg_tau['long'],
            lat = stats_hw_neg_tau['lat'],
    #                 name = stat['trend'],
            text = stats_hw_neg_tau['name'],
    #             textposition='top right',
    #             textfont=dict(
    #                 size=20,
    #                 color='black'
            customdata=stats_hw_neg_tau[['site_id','p','Tau','trend','name']],
            hovertemplate =
                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>',     
            name = 'USGS sites - neg trending',
            showlegend=False,
            marker=go.scattermapbox.Marker(
                size=small_circle,
                color=stats_hw_neg_tau['p'],
                colorscale=color_scale_decr,
                cmin=0,
                cmax=1,
                colorbar = dict(title='P Value - Decr Trend', y=0.25, len=0.5),
    #                 showscale=True,
                symbol='circle',
                )
    )

    traces.append(trace)

#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = stat_mf_neg_tau['long'],
#             lat = stat_mf_neg_tau['lat'],
#             text = stat_mf_neg_tau['site_name'],
#     #             textposition='top right',
#     #             textfont=dict(
#     #                 size=20,
#     #                 color='black'
#             customdata=stat_mf_neg_tau[['sites','p','tau','trend','site_name']],
#             hovertemplate = 
#                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#             name = 'Modified Flows - neg trending',
#             showlegend=False,
#             marker=go.scattermapbox.Marker(
#                 size=large_circle,
#                 color=stat_mf_neg_tau['p'],
#                 colorscale=color_scale_decr,
#                 cmin=0,
#                 cmax=1,
#     #             colorbar = dict(title='p values'),
#     #                 showscale=True,
#                 symbol='circle'
#             )
#     )
#     traces.append(trace)  


    # increasing----------------------------------------------   

    trace = go.Scattermapbox(
            mode='markers',
            lon = stats_hw_pos_tau['long'],
            lat = stats_hw_pos_tau['lat'],
    #                 name = stat['trend'],
            text = stats_hw_pos_tau['name'],
    #             textposition='top right',
    #             textfont=dict(
    #                 size=20,
    #                 color='black'
            customdata=stats_hw_pos_tau[['site_id','p','Tau','trend','name']],
            hovertemplate = 
               '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
            name = 'USGS sites - pos trending',
            showlegend=False,
            marker=go.scattermapbox.Marker(
                size=small_circle,
                color=stats_hw_pos_tau['p'],
                colorscale=color_scale_incr,
                cmin=0,
                cmax=1,
                colorbar = dict(title='P Value - Incr Trend', y=0.75, len=0.5),
    #                 showscale=True,
                symbol='circle',
            )
    )
    traces.append(trace)


#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = stats_mf_pos_tau['long'],
#             lat = stats_mf_pos_tau['lat'],
#     #                 name = stat['trend'],
#             text = stats_mf_pos_tau['site_name'],
#     #             textposition='top right',
#     #             textfont=dict(
#     #                 size=20,
#     #                 color='black'
#             customdata=stats_mf_pos_tau[['sites','p','tau','trend','site_name']],
#             hovertemplate = 
#                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#             name = 'Modified Flows - pos trending',
#             showlegend=False,
#             marker=go.scattermapbox.Marker(
#                 size=large_circle,
#                 color=stats_mf_pos_tau['p'],
#                 colorscale=color_scale_incr,
#                 cmin=0,
#                 cmax=1,
#     #                 showscale=True,
#                 symbol='circle',

#         ))
#     traces.append(trace) 






# decreasing------------------------------------
#     print(stat_ca_neg_tau)
    trace = go.Scattermapbox(
        mode='markers',
        lon = [float(long.iloc[0]) for long in stats_ca_neg_tau['long']], #stat_ca_neg_tau['long'],
        lat = [float(lat.iloc[0]) for lat in stats_ca_neg_tau['lat']], #stat_ca_neg_tau['lat'],
#                 name = stat['trend'],
        text = stats_ca_neg_tau['name'],
#             textposition='top right',
#             textfont=dict(
#                 size=20,
#                 color='black'
        customdata=stats_ca_neg_tau[['site_id','p','Tau','trend','name']],
        hovertemplate =
            '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>',     
        name = 'Canadian sites - neg trending',
        showlegend=False,
        marker=go.scattermapbox.Marker(
            size=small_circle,
            color=stats_ca_neg_tau['p'],
            colorscale=color_scale_decr,
            cmin=0,
            cmax=1,
#             colorbar = dict(title='P Value - Decr Trend', y=0.25, len=0.5),
#                 showscale=True,
            symbol='circle',
            )
    )

    traces.append(trace)



# increasing----------------------------------------------   

    trace = go.Scattermapbox(
        mode='markers',
        lon = [float(long.iloc[0]) for long in stats_ca_pos_tau['long']], #stat_ca_pos_tau['long'],
        lat = [float(lat.iloc[0]) for lat in stats_ca_pos_tau['lat']],
        text = stats_ca_pos_tau['name'],
#             textposition='top right',
#             textfont=dict(
#                 size=10,
#                 color='black'
        customdata=stats_ca_pos_tau[['site_id','p','Tau','trend','name']],
        hovertemplate = 
           '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
        name = 'Canadian sites - pos trending',
        showlegend=False,
        marker=go.scattermapbox.Marker(
            size=small_circle,
            color=stats_ca_pos_tau['p'],
            colorscale=color_scale_incr,
            cmin=0,
            cmax=1,
#             colorbar = dict(title='p values'),
#                 showscale=True,
            symbol='circle',
        )
    )
    traces.append(trace)


    #--------- purely to get grey symbols on legend ----------
    #Just ploting one single point that is without a trend (p>0.6) and then using these traces for the legend.

#     stats_hw_nuetral = stats_hw[stats_hw["p"]>.6].iloc[0,:]
#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = [stats_hw_nuetral['long']],
#             lat = [stats_hw_nuetral['lat']],
#     #                 name = stat['trend'],
#             text = [stats_hw_nuetral['name']],
#     #             textposition='top right',
#     #             textfont=dict(
#     #                 size=20,
#     #                 color='black'
#             customdata=stats_hw_nuetral[['site_id','p','Tau','trend','name']],
#             hovertemplate = 
#                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#             name = 'USGS and EC Sites',
#             showlegend=True,
#             marker=go.scattermapbox.Marker(
#                 size=small_circle,
#                 color='grey',
#                 colorscale=color_scale_incr,
#                 cmin=0,
#                 cmax=1,
#                 symbol='circle',
#         ))
#     traces.append(trace) 

#     stat_mf_nuetral = stat_mf[stat_mf["p"]>.6].iloc[0,:]
#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = [stat_hw_nuetral['long']],
#             lat = [stat_hw_nuetral['lat']],
#     #                 name = stat['trend'],
#             text = [stat_hw_nuetral['site_name']],
#     #             textposition='top right',
#     #             textfont=dict(
#     #                 size=20,
#     #                 color='black'
#             customdata=stat_hw_nuetral[['sites','p','tau','trend','site_name']],
#             hovertemplate = 
#                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#             name = 'Modified Flows',
#             showlegend=True,
#             marker=go.scattermapbox.Marker(
#                 size=large_circle,
#                 color='grey',
#                 colorscale=color_scale_incr,
#                 cmin=0,
#                 cmax=1,
#                 symbol='circle',
#         ))
#     traces.append(trace) 


    #------------

    layout = go.Layout(
        mapbox_layers=[
            {
                "below": 'traces',
                "sourcetype": "raster",
                "sourceattribution": "United States Geological Survey",
                "source": [
                    "https://basemap.nationalmap.gov/arcgis/rest/services/USGSHydroCached/MapServer/tile/{z}/{y}/{x}"
                ],
            }
        ],        
        mapbox = {
    #         'style': "stamen-terrain",
            'style': 'carto-positron',#'outdoors', #'stamen-terrain',  
            'zoom':4.5,
            'center': go.layout.mapbox.Center(lat=46.1, lon=-117.5)
        },
        title=f'<b>{title}</b>',
        showlegend=True,
        legend=dict(x=0.5, y=0, traceorder='normal', orientation='h'),
        autosize=True,
        width=1100,
        height=900
    )

    fig = go.Figure(data=traces, layout=layout)
    fig.show()
    figs.append(fig)



file_name = f'mk_monthly_headwater_sites{start_date}to{end_date}.html'
if os.path.exists(file_name):
    os.remove(file_name)
for figure in figs:
    with open(file_name, 'a') as f:
        f.write(figure.to_html(full_html=False, include_plotlyjs='cdn', default_width=1200, default_height=400))

In [196]:
stats_hw_nuetral

site_id                                               12324590
lat                                                  46.519483
long                                               -112.793172
name                Little Blackfoot River near Garrison MT ST
Site Type                                                 USGS
trend                                                 no trend
h                                                        False
p                                                     0.695645
z                                                     0.391206
Tau                                                   0.037736
s                                                         52.0
var_s                                             16995.333333
slope                                                 0.009079
intercept                                             6.290035
trend_color1                                               NaN
trend_color2                                rgb(186, 228, 179)
trend_color                                 rgb(186, 228, 179)
confidence_level                                     30.435491
Name: 3, dtype: object

In [ ]:
figs = []
small_circle = 8
large_circle = 13
#      dates_ranges = {'01-01':'04-01', '04-01':'07-31', '08-01':'09-30', '10-01':'12-31'} 
for stat in [peak_runoffQ, peak_runoffDOY, ThresholdVol, ThresholdDOY, total_vol, RunoffVol, SummerVol, FallVol, WinterVol]:
    if stat is peak_runoffQ:
        title=peak_runoffQ_title
    elif stat is peak_runoffDOY:
        title=peak_runoffDOY_title
    elif stat is ThresholdVol:
        title=ThresholdVol_title
    elif stat is ThresholdDOY:
        title=ThresholdDOY_title
    elif stat is total_vol:
        title=total_vol_title
    elif stat is RunoffVol:
        title=RunoffVol_title
    elif stat is SummerVol:
        title=SummerVol_title
    elif stat is WinterVol:
        title=WinterVol_title
    elif stat is FallVol:
        title=FallVol_title

#     trend_mapping = {'decreasing': 0, 'no trend': 1, 'increasing': 2}
#     stat = FallVol#, WinterVol, peak_runoffQ
#     stat['trend_numeric'] = stat['trend'].map(trend_mapping)

#         color_scale_decr = [
#             [0.0, 'rgb(128,128,128)'],
#             [0.85, 'rgb(128,128,128)'],
#             [0.851, 'rgb(254,224,144)'],
#             [0.9, 'rgb(253,174,97)'],
#             [.95, 'rgb(215, 48, 39)'],
#             [1.0, 'rgb(165,0,38)']
#         ]

#         color_scale_incr = [
#             [0.0, 'rgb(128,128,128)'],
#             [0.85, 'rgb(128,128,128)'],
#             [0.851, 'rgb(239,243,255)'],
#             [0.9, 'rgb(189,215,231)'],
#             [.95, 'rgb(49,130,189)'],
#             [1.0, 'rgb(8,81,156)']
#         ]
    color_scale_decr = [
        [0.0, 'rgb(165,0,38)'],
        [0.05, 'rgb(215, 48, 39)'],
        [0.1, 'rgb(244,109,67)'],
        [0.15, 'rgb(253,174,97)'],
#             [.2, 'rgb(254,224,144)'],
        [.1501, 'rgb(128,128,128)'],
        [1.0, 'rgb(128,128,128)']
    ]

#         #blues
#         color_scale_incr = [
#             [0.0, 'rgb(8,81,156)'],
#             [0.05, 'rgb(49,130,189)'],
#             [0.1, 'rgb(107,174,214)'],
#             [0.15, 'rgb(189,215,231)'],
#             [.2, 'rgb(239,243,255)'],
#             [.21, 'rgb(128,128,128)'],
#             [1.0, 'rgb(128,128,128)']
#         ]
    #greens
    color_scale_incr = [
        [0.0, 'rgb(0, 109, 44)'],
        [0.05, 'rgb(49, 163, 84)'],
        [0.1, 'rgb(116, 196, 118)'],
        [0.15, 'rgb(186, 228, 179)'],
#             [.2, 'rgb(237,248,233)'],
        [.1501, 'rgb(128,128,128)'],
        [1.0, 'rgb(128,128,128)']
    ]


    # Create bins for p values
    bins = np.linspace(0, 1, num=len(color_scale_decr))

    def get_color_decr(p):
        for i in range(len(bins) - 1):
            if bins[i] <= p < bins[i + 1]:
                return color_scale_decr[i][1]
        return color_scale_decr[-1][1]

    def get_color_incr(p):
        for i in range(len(bins) - 1):
            if bins[i] <= p < bins[i + 1]:
                return color_scale_incr[i][1]
        return color_scale_incr[-1][1]

    # Apply color to each record based on p value

    stat['trend_color1'] = stat[stat['tau']<0]['p'].apply(get_color_decr)
    stat['trend_color2'] = stat[stat['tau']>=0]['p'].apply(get_color_incr)
    stat['trend_color'] = stat['trend_color1'].combine_first(stat['trend_color2'])

    stat['confidence_level'] = (1 - stat['p'])*100

    stat_hw = stat[stat['site_type']=='headwater']
    stat_hw_pos_tau = stat_hw[stat_hw["tau"]>0]
    stat_hw_neg_tau = stat_hw[stat_hw["tau"]<=0]

    stat_mf = stat[stat['site_type']=='modified flows']
    stat_mf_pos_tau = stat_mf[stat_mf["tau"]>0]
    stat_mf_neg_tau = stat_mf[stat_mf["tau"]<=0]

    stat_ca = stat[stat['site_type']=='canadian']
    stat_ca_pos_tau = stat_ca[stat_ca["tau"]>0]
    stat_ca_neg_tau = stat_ca[stat_ca["tau"]<=0]

    traces = []


    # decreasing------------------------------------

    trace = go.Scattermapbox(
            mode='markers',
            lon = stat_hw_neg_tau['long'],
            lat = stat_hw_neg_tau['lat'],
    #                 name = stat['trend'],
            text = stat_hw_neg_tau['site_name'],
    #             textposition='top right',
    #             textfont=dict(
    #                 size=20,
    #                 color='black'
            customdata=stat_hw_neg_tau[['sites','p','tau','trend','site_name']],
            hovertemplate =
                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>',     
            name = 'USGS sites - neg trending',
            showlegend=False,
            marker=go.scattermapbox.Marker(
                size=small_circle,
                color=stat_hw_neg_tau['p'],
                colorscale=color_scale_decr,
                cmin=0,
                cmax=1,
                colorbar = dict(title='P Value - Decr Trend', y=0.25, len=0.5),
    #                 showscale=True,
                symbol='circle',
                )
    )

    traces.append(trace)

#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = stat_mf_neg_tau['long'],
#             lat = stat_mf_neg_tau['lat'],
#             text = stat_mf_neg_tau['site_name'],
#     #             textposition='top right',
#     #             textfont=dict(
#     #                 size=20,
#     #                 color='black'
#             customdata=stat_mf_neg_tau[['sites','p','tau','trend','site_name']],
#             hovertemplate = 
#                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#             name = 'Modified Flows - neg trending',
#             showlegend=False,
#             marker=go.scattermapbox.Marker(
#                 size=large_circle,
#                 color=stat_mf_neg_tau['p'],
#                 colorscale=color_scale_decr,
#                 cmin=0,
#                 cmax=1,
#     #             colorbar = dict(title='p values'),
#     #                 showscale=True,
#                 symbol='circle'
#             )
#     )
#     traces.append(trace)  


    # increasing----------------------------------------------   

    trace = go.Scattermapbox(
            mode='markers',
            lon = stat_hw_pos_tau['long'],
            lat = stat_hw_pos_tau['lat'],
    #                 name = stat['trend'],
            text = stat_hw_pos_tau['site_name'],
    #             textposition='top right',
    #             textfont=dict(
    #                 size=20,
    #                 color='black'
            customdata=stat_hw_pos_tau[['sites','p','tau','trend','site_name']],
            hovertemplate = 
               '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
            name = 'USGS sites - pos trending',
            showlegend=False,
            marker=go.scattermapbox.Marker(
                size=small_circle,
                color=stat_hw_pos_tau['p'],
                colorscale=color_scale_incr,
                cmin=0,
                cmax=1,
                colorbar = dict(title='P Value - Incr Trend', y=0.75, len=0.5),
    #                 showscale=True,
                symbol='circle',
            )
    )
    traces.append(trace)


#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = stat_mf_pos_tau['long'],
#             lat = stat_mf_pos_tau['lat'],
#     #                 name = stat['trend'],
#             text = stat_mf_pos_tau['site_name'],
#     #             textposition='top right',
#     #             textfont=dict(
#     #                 size=20,
#     #                 color='black'
#             customdata=stat_mf_pos_tau[['sites','p','tau','trend','site_name']],
#             hovertemplate = 
#                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#             name = 'Modified Flows - pos trending',
#             showlegend=False,
#             marker=go.scattermapbox.Marker(
#                 size=large_circle,
#                 color=stat_mf_pos_tau['p'],
#                 colorscale=color_scale_incr,
#                 cmin=0,
#                 cmax=1,
#     #                 showscale=True,
#                 symbol='circle',

#         ))
#     traces.append(trace) 






# decreasing------------------------------------
#     print(stat_ca_neg_tau)
    trace = go.Scattermapbox(
        mode='markers',
        lon = [float(long.iloc[0]) for long in stat_ca_neg_tau['long']], #stat_ca_neg_tau['long'],
        lat = [float(lat.iloc[0]) for lat in stat_ca_neg_tau['lat']], #stat_ca_neg_tau['lat'],
#                 name = stat['trend'],
        text = stat_ca_neg_tau['site_name'],
#             textposition='top right',
#             textfont=dict(
#                 size=20,
#                 color='black'
        customdata=stat_ca_neg_tau[['sites','p','tau','trend','site_name']],
        hovertemplate =
            '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>',     
        name = 'Canadian sites - neg trending',
        showlegend=False,
        marker=go.scattermapbox.Marker(
            size=small_circle,
            color=stat_ca_neg_tau['p'],
            colorscale=color_scale_decr,
            cmin=0,
            cmax=1,
#             colorbar = dict(title='P Value - Decr Trend', y=0.25, len=0.5),
#                 showscale=True,
            symbol='circle',
            )
    )

    traces.append(trace)



# increasing----------------------------------------------   

    trace = go.Scattermapbox(
        mode='markers',
        lon = [float(long.iloc[0]) for long in stat_ca_pos_tau['long']], #stat_ca_pos_tau['long'],
        lat = [float(lat.iloc[0]) for lat in stat_ca_pos_tau['lat']],
        text = stat_ca_pos_tau['site_name'],
#             textposition='top right',
#             textfont=dict(
#                 size=10,
#                 color='black'
        customdata=stat_ca_pos_tau[['sites','p','tau','trend','site_name']],
        hovertemplate = 
           '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
        name = 'Canadian sites - pos trending',
        showlegend=False,
        marker=go.scattermapbox.Marker(
            size=small_circle,
            color=stat_ca_pos_tau['p'],
            colorscale=color_scale_incr,
            cmin=0,
            cmax=1,
#             colorbar = dict(title='p values'),
#                 showscale=True,
            symbol='circle',
        )
    )
    traces.append(trace)


    #--------- purely to get grey symbols on legend ----------
    #Just ploting one single point that is without a trend (p>0.6) and then using these traces for the legend.

    stat_hw_nuetral = stat_hw[stat_hw["p"]>.6].iloc[0,:]
    trace = go.Scattermapbox(
            mode='markers',
            lon = [stat_hw_nuetral['long']],
            lat = [stat_hw_nuetral['lat']],
    #                 name = stat['trend'],
            text = [stat_hw_nuetral['site_name']],
    #             textposition='top right',
    #             textfont=dict(
    #                 size=20,
    #                 color='black'
            customdata=stat_hw_nuetral[['sites','p','tau','trend','site_name']],
            hovertemplate = 
               '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
            name = 'USGS and EC Sites',
            showlegend=True,
            marker=go.scattermapbox.Marker(
                size=small_circle,
                color='grey',
                colorscale=color_scale_incr,
                cmin=0,
                cmax=1,
                symbol='circle',
        ))
    traces.append(trace) 

#     stat_mf_nuetral = stat_mf[stat_mf["p"]>.6].iloc[0,:]
#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = [stat_hw_nuetral['long']],
#             lat = [stat_hw_nuetral['lat']],
#     #                 name = stat['trend'],
#             text = [stat_hw_nuetral['site_name']],
#     #             textposition='top right',
#     #             textfont=dict(
#     #                 size=20,
#     #                 color='black'
#             customdata=stat_hw_nuetral[['sites','p','tau','trend','site_name']],
#             hovertemplate = 
#                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>p value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#             name = 'Modified Flows',
#             showlegend=True,
#             marker=go.scattermapbox.Marker(
#                 size=large_circle,
#                 color='grey',
#                 colorscale=color_scale_incr,
#                 cmin=0,
#                 cmax=1,
#                 symbol='circle',
#         ))
#     traces.append(trace) 


    #------------

    layout = go.Layout(
        mapbox_layers=[
            {
                "below": 'traces',
                "sourcetype": "raster",
                "sourceattribution": "United States Geological Survey",
                "source": [
                    "https://basemap.nationalmap.gov/arcgis/rest/services/USGSHydroCached/MapServer/tile/{z}/{y}/{x}"
                ],
            }
        ],        
        mapbox = {
    #         'style': "stamen-terrain",
            'style': 'carto-positron',#'outdoors', #'stamen-terrain',  
            'zoom':4.5,
            'center': go.layout.mapbox.Center(lat=46.1, lon=-117.5)
        },
        title=f'<b>{title}</b>',
        showlegend=True,
        legend=dict(x=0.5, y=0, traceorder='normal', orientation='h'),
        autosize=True,
        width=1100,
        height=900
    )

    fig = go.Figure(data=traces, layout=layout)
    fig.show()
    figs.append(fig)



file_name = f'mk_maps_usgs_ca_sites{start_date}to{end_date}.html'
if os.path.exists(file_name):
    os.remove(file_name)
for figure in figs:
    with open(file_name, 'a') as f:
        f.write(figure.to_html(full_html=False, include_plotlyjs='cdn', default_width=1200, default_height=400))

In [ ]:
stat_ca

In [ ]:
traces

In [ ]:
pd.DataFrame(volume_stats_mf)

In [ ]:
# figs = []
# #      dates_ranges = {'01-01':'04-01', '04-01':'07-31', '08-01':'09-30', '10-01':'12-31'} 
# for stat in [peak_runoffQ, peak_runoffDOY, ThresholdVol, ThresholdDOY, total_vol, RunoffVol, SummerVol, FallVol, WinterVol]:
#     if stat is peak_runoffQ:
#         title=peak_runoffQ_title
#     elif stat is peak_runoffDOY:
#         title=peak_runoffDOY_title
#     elif stat is ThresholdVol:
#         title=ThresholdVol_title
#     elif stat is ThresholdDOY:
#         title=ThresholdDOY_title
#     elif stat is total_vol:
#         title=total_vol_title
#     elif stat is RunoffVol:
#         title=RunoffVol_title
#     elif stat is SummerVol:
#         title=SummerVol_title
#     elif stat is WinterVol:
#         title=WinterVol_title
#     elif stat is FallVol:
#         title=FallVol_title

# #     stat = FallVol#, WinterVol, peak_runoffQ
# #     stat['trend_numeric'] = stat['trend'].map(trend_mapping)

#     color_scale_decr = [
#         [0.0, 'rgb(165,0,38)'],
#         [0.05, 'rgb(215, 48, 39)'],
#         [0.1, 'rgb(244,109,67)'],
#         [0.15, 'rgb(253,174,97)'],
#         [.2, 'rgb(254,224,144)'],
#         [.21, 'rgb(128,128,128)'],
#         [1.0, 'rgb(128,128,128)']
#     ]

#     color_scale_incr = [
#         [0.0, 'rgb(8,81,156)'],
#         [0.05, 'rgb(49,130,189)'],
#         [0.1, 'rgb(107,174,214)'],
#         [0.15, 'rgb(189,215,231)'],
#         [.2, 'rgb(239,243,255)'],
#         [.21, 'rgb(128,128,128)'],
#         [1.0, 'rgb(128,128,128)']
#     ]


#     # Create bins for p values
#     bins = np.linspace(0, 1, num=len(color_scale_decr))

#     def get_color_decr(p):
#         for i in range(len(bins) - 1):
#             if bins[i] <= p < bins[i + 1]:
#                 return color_scale_decr[i][1]
#         return color_scale_decr[-1][1]

#     def get_color_incr(p):
#         for i in range(len(bins) - 1):
#             if bins[i] <= p < bins[i + 1]:
#                 return color_scale_incr[i][1]
#         return color_scale_incr[-1][1]

#     # Apply color to each record based on p value

#     stat['trend_color1'] = stat[stat['tau']<0]['p'].apply(get_color_decr)
#     stat['trend_color2'] = stat[stat['tau']>=0]['p'].apply(get_color_incr)
#     stat['trend_color'] = stat['trend_color1'].combine_first(stat['trend_color2'])

#     stat_hw = stat[stat['site_type']=='headwater']
#     stat_hw_pos_tau = stat_hw[stat_hw["tau"]>0]
#     stat_hw_neg_tau = stat_hw[stat_hw["tau"]<=0]

#     stat_mf = stat[stat['site_type']=='modified flows']
#     stat_mf_pos_tau = stat_mf[stat_mf["tau"]>0]
#     stat_mf_neg_tau = stat_mf[stat_mf["tau"]<=0]

#     # trends = ['decreasing', 'no trend', 'increasing']
#     # trends_numerics = [0, 1, 2]
#     # markers = ['circle', 'circle-stroked', 'information']
#     # colors = ['red', 'grey', 'blue']
#     # site_types = ['modified flows', 'headwater']
#     # symbol_map = {'modified flows': 'square', 'headwater': 'circle'}

#     traces = []


#     # decreasing------------------------------------

#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = stat_hw_neg_tau['long'],
#             lat = stat_hw_neg_tau['lat'],
#     #                 name = stat['trend'],
#             text = stat_hw_neg_tau['site_name'],
#     #             textposition='top right',
#     #             textfont=dict(
#     #                 size=20,
#     #                 color='black'
#             customdata=stat_hw_neg_tau[['sites','p','tau','trend','site_name']],
#             hovertemplate =
#                 '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>P-value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>',     
#             name = 'USGS sites - neg trending',
#             showlegend=False,
#             marker=go.scattermapbox.Marker(
#                 size=7,
#                 color=stat_hw_neg_tau['p'],
#                 colorscale=color_scale_decr,
#                 cmin=0,
#                 cmax=1,
#                 colorbar = dict(title='p values - Decr Trend', y=0.25, len=0.5),
#     #                 showscale=True,
#                 symbol='circle',
#                 )
#     )

#     traces.append(trace)

#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = stat_mf_neg_tau['long'],
#             lat = stat_mf_neg_tau['lat'],
#             text = stat_mf_neg_tau['site_name'],
#     #             textposition='top right',
#     #             textfont=dict(
#     #                 size=20,
#     #                 color='black'
#             customdata=stat_mf_neg_tau[['sites','p','tau','trend','site_name']],
#             hovertemplate = 
#                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>P-value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#             name = 'Modified Flows - neg trending',
#             showlegend=False,
#             marker=go.scattermapbox.Marker(
#                 size=10,
#                 color=stat_mf_neg_tau['p'],
#                 colorscale=color_scale_decr,
#                 cmin=0,
#                 cmax=1,
#     #             colorbar = dict(title='p values'),
#     #                 showscale=True,
#                 symbol='circle'
#             )
#     )
#     traces.append(trace)  


#     # increasing----------------------------------------------   

#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = stat_hw_pos_tau['long'],
#             lat = stat_hw_pos_tau['lat'],
#     #                 name = stat['trend'],
#             text = stat_hw_pos_tau['site_name'],
#     #             textposition='top right',
#     #             textfont=dict(
#     #                 size=20,
#     #                 color='black'
#             customdata=stat_hw_pos_tau[['sites','p','tau','trend','site_name']],
#             hovertemplate = 
#                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>P-value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#             name = 'USGS sites - pos trending',
#             showlegend=False,
#             marker=go.scattermapbox.Marker(
#                 size=6,
#                 color=stat_hw_pos_tau['p'],
#                 colorscale=color_scale_incr,
#                 cmin=0,
#                 cmax=1,
#     #             colorbar = dict(title='p values'),
#     #                 showscale=True,
#                 symbol='circle',
#             )
#     )
#     traces.append(trace)


#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = stat_mf_pos_tau['long'],
#             lat = stat_mf_pos_tau['lat'],
#     #                 name = stat['trend'],
#             text = stat_mf_pos_tau['site_name'],
#     #             textposition='top right',
#     #             textfont=dict(
#     #                 size=20,
#     #                 color='black'
#             customdata=stat_mf_pos_tau[['sites','p','tau','trend','site_name']],
#             hovertemplate = 
#                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>P-value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#             name = 'Modified Flows - pos trending',
#             showlegend=False,
#             marker=go.scattermapbox.Marker(
#                 size=11,
#                 color=stat_mf_pos_tau['p'],
#                 colorscale=color_scale_incr,
#                 cmin=0,
#                 cmax=1,
#                 colorbar = dict(title='p values - Incr Trend', len=0.5,y=.77),
#     #                 showscale=True,
#                 symbol='circle',

#         ))
#     traces.append(trace) 


#     #--------- purely to get grey symbols on legend ----------
#     #Just ploting one single point that is without a trend (p>0.6) and then using these traces for the legend.

#     stat_hw_nuetral = stat_hw[stat_hw["p"]>.6].iloc[0,:]
#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = [stat_hw_nuetral['long']],
#             lat = [stat_hw_nuetral['lat']],
#     #                 name = stat['trend'],
#             text = [stat_hw_nuetral['site_name']],
#     #             textposition='top right',
#     #             textfont=dict(
#     #                 size=20,
#     #                 color='black'
#             customdata=stat_hw_nuetral[['sites','p','tau','trend','site_name']],
#             hovertemplate = 
#                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>P-value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#             name = 'USGS Sites',
#             showlegend=True,
#             marker=go.scattermapbox.Marker(
#                 size=5,
#                 color='grey',
#                 colorscale=color_scale_incr,
#                 cmin=0,
#                 cmax=1,
#                 symbol='circle',
#         ))
#     traces.append(trace) 

#     stat_mf_nuetral = stat_mf[stat_mf["p"]>.6].iloc[0,:]
#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = [stat_mf_nuetral['long']],
#             lat = [stat_mf_nuetral['lat']],
#     #                 name = stat['trend'],
#             text = [stat_mf_nuetral['site_name']],
#     #             textposition='top right',
#     #             textfont=dict(
#     #                 size=20,
#     #                 color='black'
#             customdata=stat_mf_nuetral[['sites','p','tau','trend','site_name']],
#             hovertemplate = 
#                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>P-value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#             name = 'Modified Flows',
#             showlegend=True,
#             marker=go.scattermapbox.Marker(
#                 size=11,
#                 color='grey',
#                 colorscale=color_scale_incr,
#                 cmin=0,
#                 cmax=1,
#                 symbol='circle',
#         ))
#     traces.append(trace) 


#     #------------

#     layout = go.Layout(
#         mapbox_layers=[
#             {
#                 "below": 'traces',
#                 "sourcetype": "raster",
#                 "sourceattribution": "United States Geological Survey",
#                 "source": [
#                     "https://basemap.nationalmap.gov/arcgis/rest/services/USGSHydroCached/MapServer/tile/{z}/{y}/{x}"
#                 ],
#             }
#         ],        
#         mapbox = {
#     #         'style': "stamen-terrain",
#             'style': 'carto-positron',#'outdoors', #'stamen-terrain',  
#             'zoom':5,
#             'center': go.layout.mapbox.Center(lat=46.1, lon=-117.5)
#         },
#         title=f'<b>{title}</b>',
#         showlegend=True,
#         legend=dict(x=0.5, y=-0.1, traceorder='normal', orientation='h'),
#         autosize=True,
#         width=900,
#         height=700
#     )

#     fig = go.Figure(data=traces, layout=layout)
#     fig.show()
#     figs.append(fig)

In [ ]:
# ## Works well but doesn't distinguish between increasing and decreasing trends.  Awesome scale bar for p values though.

# trend_mapping = {'decreasing': 0, 'no trend': 1, 'increasing': 2}


# stat = WinterVol #peak_runoffQ
# stat['trend_numeric'] = stat['trend'].map(trend_mapping)

# # color_scale = [
# #     [0.0, 'rgb(165,0,38)'],
# #     [0.1, 'rgb(215,48,39)'],
# #     [0.2, 'rgb(244,109,67)'],
# #     [0.3, 'rgb(253,174,97)'],
# #     [0.4, 'rgb(254,224,144)'],
# #     [0.5, 'rgb(224,243,248)'],
# #     [0.6, 'rgb(171,217,233)'],
# #     [0.7, 'rgb(116,173,209)'],
# #     [0.8, 'rgb(69,117,180)'],
# #     [0.9, 'rgb(49,54,149)'],
# #     [1.0, 'rgb(2,56,88)']
# # ]
# color_scale = [
#     [0.0, 'rgb(165,0,38)'],
#     [0.05, 'rgb(215, 48, 39)'],
#     [0.1, 'rgb(244,109,67)'],
#     [0.15, 'rgb(253,174,97)'],
#     [.2, 'rgb(254,224,144)'],
#     [.21, 'rgb(128,128,128)'],
#     [1.0, 'rgb(128,128,128)']
# ]

# # Create bins for p values
# bins = np.linspace(0, 1, num=len(color_scale))

# def get_color(p):
#     for i in range(len(bins) - 1):
#         if bins[i] <= p < bins[i + 1]:
#             return color_scale[i][1]
#     return color_scale[-1][1]

# # Apply color to each record based on p value
# stat['trend_color'] = stat['p'].apply(get_color)
# stat_hw = peak_runoffQ[peak_runoffQ['site_type']=='headwater']
# stat_mf = peak_runoffQ[peak_runoffQ['site_type']=='modified flows']


# trends = ['decreasing', 'no trend', 'increasing']
# trends_numerics = [0, 1, 2]
# markers = ['circle', 'circle-stroked', 'information']
# colors = ['red', 'grey', 'blue']
# site_types = ['modified flows', 'headwater']
# symbol_map = {'modified flows': 'square', 'headwater': 'circle'}

# traces = []
# # fig = go.Figure()
# for trend, color in zip(trends, colors):
# # for site_type, group in stat.groupby('site_type'):
#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = stat_hw[stat_hw["trend"]==trend]['long'],
#             lat = stat_hw[stat_hw["trend"]==trend]['lat'],
# #                 name = stat['trend'],
#             text = stat_hw[stat_hw["trend"]==trend]['site_name'],
# #             textposition='top right',
# #             textfont=dict(
# #                 size=20,
# #                 color='black'
#             customdata=stat_hw[stat_hw["trend"]==trend][['sites','p','tau','trend','site_name']],
#             hovertemplate = 
#                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>P-value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information

#             marker=go.scattermapbox.Marker(
#                 size=10,
#                 color=stat_hw[stat_hw["trend"]==trend]['p'],
#                 colorscale=color_scale,
#                 cmin=0,
#                 cmax=1,
#                 colorbar = dict(title='p values'),
# #                 showscale=True,
#                 symbol='circle', 
#         ))
#     traces.append(trace)


# for trend, color in zip(trends, colors):
# # for site_type, group in stat.groupby('site_type'):
#     trace = go.Scattermapbox(
#             mode='markers',
#             lon = stat_mf[stat_mf["trend"]==trend]['long'],
#             lat = stat_mf[stat_mf["trend"]==trend]['lat'],
# #                 name = stat['trend'],
#             text = stat_mf[stat_mf["trend"]==trend]['site_name'],
# #             textposition='top right',
# #             textfont=dict(
# #                 size=20,
# #                 color='black'
#             customdata=stat_mf[stat_mf["trend"]==trend][['sites','p','tau','trend','site_name']],
#             hovertemplate = 
#                '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>P-value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information

#             marker=go.scattermapbox.Marker(
#                 size=10,
#                 color=stat_mf[stat_mf["trend"]==trend]['p'],
#                 colorscale=color_scale,
#                 cmin=0,
#                 cmax=1,
#                 colorbar = dict(title='p values'),
# #                 showscale=True,
#                 symbol='circle', 
#         ))
#     traces.append(trace)
    
    
# layout = go.Layout(
# # fig.update_layout(

# #     mapbox_layers=[
# #         {
# #             "below": 'traces',
# #             "sourcetype": "raster",
# #             "sourceattribution": "United States Geological Survey",
# #             "source": [
# #                 "https://basemap.nationalmap.gov/arcgis/rest/services/USGSHydroCached/MapServer/tile/{z}/{y}/{x}"
# #             ],
# #         }
# #     ],        
#     mapbox = {
# #         'style': "stamen-terrain",
#         'style': 'outdoors',#'carto-positron', #'stamen-terrain',  
#         'zoom':5,
#         'center': go.layout.mapbox.Center(lat=46.1, lon=-117.5)
#     },
#     title=f'<b>{title}</b>',
#     showlegend=False,
#     autosize=True,
#     width=900,
#     height=700
# )

# fig = go.Figure(data=traces, layout=layout)
# fig.show()

In [ ]:
# trend_mapping = {'decreasing': 0, 'no trend': 1, 'increasing': 2}


# stat = FallVol#, WinterVol, peak_runoffQ
# stat['trend_numeric'] = stat['trend'].map(trend_mapping)

# # color_scale = [
# #     [0.0, 'rgb(165,0,38)'],
# #     [0.1, 'rgb(215,48,39)'],
# #     [0.2, 'rgb(244,109,67)'],
# #     [0.3, 'rgb(253,174,97)'],
# #     [0.4, 'rgb(254,224,144)'],
# #     [0.5, 'rgb(224,243,248)'],
# #     [0.6, 'rgb(171,217,233)'],
# #     [0.7, 'rgb(116,173,209)'],
# #     [0.8, 'rgb(69,117,180)'],
# #     [0.9, 'rgb(49,54,149)'],
# #     [1.0, 'rgb(2,56,88)']
# # ]
# color_scale_decr = [
#     [0.0, 'rgb(165,0,38)'],
#     [0.05, 'rgb(215, 48, 39)'],
#     [0.1, 'rgb(244,109,67)'],
#     [0.15, 'rgb(253,174,97)'],
#     [.2, 'rgb(254,224,144)'],
#     [.21, 'rgb(128,128,128)'],
#     [1.0, 'rgb(128,128,128)']
# ]

# color_scale_incr = [
#     [0.0, 'rgb(8,81,156)'],
#     [0.05, 'rgb(49,130,189)'],
#     [0.1, 'rgb(107,174,214)'],
#     [0.15, 'rgb(189,215,231)'],
#     [.2, 'rgb(239,243,255)'],
#     [.21, 'rgb(128,128,128)'],
#     [1.0, 'rgb(128,128,128)']
# ]


# # Create bins for p values
# bins = np.linspace(0, 1, num=len(color_scale))

# def get_color_decr(p):
#     for i in range(len(bins) - 1):
#         if bins[i] <= p < bins[i + 1]:
#             return color_scale_decr[i][1]
#     return color_scale_decr[-1][1]

# def get_color_incr(p):
#     for i in range(len(bins) - 1):
#         if bins[i] <= p < bins[i + 1]:
#             return color_scale_incr[i][1]
#     return color_scale_incr[-1][1]

# # Apply color to each record based on p value

# stat['trend_color'] = stat[stat['trend']=='decreasing']['p'].apply(get_color_decr)
# stat['trend_color'] = stat[stat['trend']=='increasing']['p'].apply(get_color_incr)

# stat_hw = stat[stat['site_type']=='headwater']
# stat_mf = stat[stat['site_type']=='modified flows']


# trends = ['decreasing', 'no trend', 'increasing']
# trends_numerics = [0, 1, 2]
# markers = ['circle', 'circle-stroked', 'information']
# colors = ['red', 'grey', 'blue']
# site_types = ['modified flows', 'headwater']
# symbol_map = {'modified flows': 'square', 'headwater': 'circle'}

# traces = []


# # decreasing------------------------------------

# trace = go.Scattermapbox(
#         mode='markers',
#         lon = stat_hw[stat_hw["trend"]=='decreasing']['long'],
#         lat = stat_hw[stat_hw["trend"]=='decreasing']['lat'],
# #                 name = stat['trend'],
#         text = stat_hw[stat_hw["trend"]=='decreasing']['site_name'],
# #             textposition='top right',
# #             textfont=dict(
# #                 size=20,
# #                 color='black'
#         customdata=stat_hw[stat_hw["trend"]=='decreasing'][['sites','p','tau','trend','site_name']],
#         hovertemplate = 
#        '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>P-value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information

#         marker=go.scattermapbox.Marker(
#             size=10,
#             color=stat_hw[stat_hw["trend"]=='decreasing']['p'],
#             colorscale=color_scale_decr,
#             cmin=0,
#             cmax=1,
#             colorbar = dict(title='p values - Decr Trend', y=0.25, len=0.5),
# #                 showscale=True,
#             symbol='circle', 
#     ))
# traces.append(trace)

# trace = go.Scattermapbox(
#         mode='markers',
#         lon = stat_mf[stat_mf["trend"]=='decreasing']['long'],
#         lat = stat_mf[stat_mf["trend"]=='decreasing']['lat'],
# #                 name = stat['trend'],
#         text = stat_mf[stat_mf["trend"]=='decreasing']['site_name'],
# #             textposition='top right',
# #             textfont=dict(
# #                 size=20,
# #                 color='black'
#         customdata=stat_mf[stat_mf["trend"]=='decreasing'][['sites','p','tau','trend','site_name']],
#         hovertemplate = 
#            '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>P-value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information

#         marker=go.scattermapbox.Marker(
#             size=10,
#             color=stat_mf[stat_mf["trend"]=='decreasing']['p'],
#             colorscale=color_scale_decr,
#             cmin=0,
#             cmax=1,
# #             colorbar = dict(title='p values'),
# #                 showscale=True,
#             symbol='circle', 
#     ))
# traces.append(trace)  


# # no trend---------------------------------------------------

# trace = go.Scattermapbox(
#         mode='markers',
#         lon = stat_hw[stat_hw["trend"]=='no trend']['long'],
#         lat = stat_hw[stat_hw["trend"]=='no trend']['lat'],
# #                 name = stat['trend'],
#         text = stat_hw[stat_hw["trend"]=='no trend']['site_name'],
# #             textposition='top right',
# #             textfont=dict(
# #                 size=20,
# #                 color='black'
#         customdata=stat_hw[stat_hw["trend"]=='no trend'][['sites','p','tau','trend','site_name']],
#         hovertemplate = 
#            '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>P-value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information

#         marker=go.scattermapbox.Marker(
#             size=10,
#             color='rgb(128,128,128)',
#             symbol='circle', 
#     ))
# traces.append(trace)

# trace = go.Scattermapbox(
#         mode='markers',
#         lon = stat_mf[stat_mf["trend"]=='no trend']['long'],
#         lat = stat_mf[stat_mf["trend"]=='no trend']['lat'],
# #                 name = stat['trend'],
#         text = stat_mf[stat_mf["trend"]=='no trend']['site_name'],
# #             textposition='top right',
# #             textfont=dict(
# #                 size=20,
# #                 color='black'
#         customdata=stat_mf[stat_mf["trend"]=='no trend'][['sites','p','tau','trend','site_name']],
#         hovertemplate = 
#            '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>P-value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information

#         marker=go.scattermapbox.Marker(
#             size=10,
#             color='rgb(128,128,128)',
#             symbol='circle', 
#     ))
# traces.append(trace)
 
    
# # increasing----------------------------------------------   
  
# trace = go.Scattermapbox(
#         mode='markers',
#         lon = stat_hw[stat_hw["trend"]=='increasing']['long'],
#         lat = stat_hw[stat_hw["trend"]=='increasing']['lat'],
# #                 name = stat['trend'],
#         text = stat_hw[stat_hw["trend"]=='increasing']['site_name'],
# #             textposition='top right',
# #             textfont=dict(
# #                 size=20,
# #                 color='black'
#         customdata=stat_hw[stat_hw["trend"]=='increasing'][['sites','p','tau','trend','site_name']],
#         hovertemplate = 
#            '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>P-value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information

#         marker=go.scattermapbox.Marker(
#             size=10,
#             color=stat_hw[stat_hw["trend"]=='increasing']['p'],
#             colorscale=color_scale_incr,
#             cmin=0,
#             cmax=1,
# #             colorbar = dict(title='p values'),
# #                 showscale=True,
#             symbol='circle', 
#     ))
# traces.append(trace)


# # for trend, color in zip(trends, colors):
# # for site_type, group in stat.groupby('site_type'):
# trace = go.Scattermapbox(
#         mode='markers',
#         lon = stat_mf[stat_mf["trend"]=='increasing']['long'],
#         lat = stat_mf[stat_mf["trend"]=='increasing']['lat'],
# #                 name = stat['trend'],
#         text = stat_mf[stat_mf["trend"]=='increasing']['site_name'],
# #             textposition='top right',
# #             textfont=dict(
# #                 size=20,
# #                 color='black'
#         customdata=stat_mf[stat_mf["trend"]=='increasing'][['sites','p','tau','trend','site_name']],
#         hovertemplate = 
#            '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>P-value: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information

#         marker=go.scattermapbox.Marker(
#             size=10,
#             color=stat_mf[stat_mf["trend"]=='increasing']['p'],
#             colorscale=color_scale_incr,
#             cmin=0,
#             cmax=1,
#             colorbar = dict(title='p values - Incr Trend', len=0.5,y=.77),
# #                 showscale=True,
#             symbol='circle', 
#     ))
# traces.append(trace) 


    
    
    
    
    
    
    
    
# layout = go.Layout(
# # fig.update_layout(

#     mapbox_layers=[
#         {
#             "below": 'traces',
#             "sourcetype": "raster",
#             "sourceattribution": "United States Geological Survey",
#             "source": [
#                 "https://basemap.nationalmap.gov/arcgis/rest/services/USGSHydroCached/MapServer/tile/{z}/{y}/{x}"
#             ],
#         }
#     ],        
#     mapbox = {
# #         'style': "stamen-terrain",
#         'style': 'carto-positron',#'outdoors', #'stamen-terrain',  
#         'zoom':5,
#         'center': go.layout.mapbox.Center(lat=46.1, lon=-117.5)
#     },
#     title=f'<b>{title}</b>',
#     showlegend=False,
#     autosize=True,
#     width=900,
#     height=700
# )

# fig = go.Figure(data=traces, layout=layout)
# fig.show()

In [ ]:
trend_mapping = {'decreasing': 0, 'no trend': 1, 'increasing': 2}


stat = peak_runoffQ
stat['trend_numeric'] = stat['trend'].map(trend_mapping)
stat['confidence_level'] = 1 - stat['p']

color_scale_decr = [
    [0.0, 'rgb(128,128,128)'],
    [0.85, 'rgb(128,128,128)'],
    [0.851, 'rgb(254,224,144)'],
    [0.9, 'rgb(253,174,97)'],
    [.95, 'rgb(215, 48, 39)'],
    [1.0, 'rgb(165,0,38)']
]

color_scale_incr = [
    [0.0, 'rgb(128,128,128)'],
    [0.85, 'rgb(128,128,128)'],
    [0.851, 'rgb(239,243,255)'],
    [0.9, 'rgb(189,215,231)'],
    [.95, 'rgb(49,130,189)'],
    [1.0, 'rgb(8,81,156)']
]

# color_scale_incr = [
#     [0.0, 'rgb(8,81,156)'],
#     [0.05, 'rgb(49,130,189)'],
#     [0.1, 'rgb(107,174,214)'],
#     [0.15, 'rgb(189,215,231)'],
#     [.2, 'rgb(239,243,255)'],
#     [.21, 'rgb(128,128,128)'],
#     [1.0, 'rgb(128,128,128)']
# ]

# color_scale_decr = [
#     [0.0, 'rgb(165,0,38)'],
#     [0.05, 'rgb(215, 48, 39)'],
#     [0.1, 'rgb(244,109,67)'],
#     [0.15, 'rgb(253,174,97)'],
#     [.2, 'rgb(254,224,144)'],
#     [.21, 'rgb(128,128,128)'],
#     [1.0, 'rgb(128,128,128)']
# ]




# Create bins for p values
bins = np.linspace(0, 1, num=len(color_scale_decr))

def get_color_decr(p):
    for i in range(len(bins) - 1):
        if bins[i] <= p < bins[i + 1]:
            return color_scale_decr[i][1]
    return color_scale_decr[-1][1]

def get_color_incr(p):
    for i in range(len(bins) - 1):
        if bins[i] <= p < bins[i + 1]:
            return color_scale_incr[i][1]
    return color_scale_incr[-1][1]

# Apply color to each record based on p value

stat['trend_color1'] = stat[stat['tau']<0]['confidence_level'].apply(get_color_decr)
stat['trend_color2'] = stat[stat['tau']>=0]['confidence_level'].apply(get_color_incr)
stat['trend_color'] = stat['trend_color1'].combine_first(stat['trend_color2'])

stat_hw = stat[stat['site_type']=='headwater']
stat_hw_pos_tau = stat_hw[stat_hw["tau"]>0]
stat_hw_neg_tau = stat_hw[stat_hw["tau"]<=0]

stat_mf = stat[stat['site_type']=='modified flows']
stat_mf_pos_tau = stat_mf[stat_mf["tau"]>0]
stat_mf_neg_tau = stat_mf[stat_mf["tau"]<=0]

# trends = ['decreasing', 'no trend', 'increasing']
# trends_numerics = [0, 1, 2]
# markers = ['circle', 'circle-stroked', 'information']
# colors = ['red', 'grey', 'blue']
# site_types = ['modified flows', 'headwater']
# symbol_map = {'modified flows': 'square', 'headwater': 'circle'}

traces = []


# decreasing------------------------------------

trace = go.Scattermapbox(
        mode='markers',
        lon = stat_hw_neg_tau['long'],
        lat = stat_hw_neg_tau['lat'],
#                 name = stat['trend'],
        text = stat_hw_neg_tau['site_name'],
#             textposition='top right',
#             textfont=dict(
#                 size=20,
#                 color='black'
        customdata=stat_hw_neg_tau[['sites','confidence_level','tau','trend','site_name']],
        hovertemplate =
            '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>Confidence Level: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>',     
        name = 'USGS sites - neg trending',
        showlegend=False,
#         marker=go.scattermapbox.Marker(
#             size=7,
#             color=stat_hw_neg_tau['confidence_level'],
#             colorscale=color_scale_decr,
#             cmin=0,
#             cmax=1,
#             colorbar = dict(title='Confidence - Decr Trend', y=0.25, len=0.5),
# #                 showscale=True,
#             ),
    #fiiiiiiiiiiii
        marker = {'size':15, 'symbol':['triangle' for i in stat_hw_neg_tau.index], 
#                   'color':stat_hw_neg_tau['confidence_level']
                 },
#         color=stat_hw_neg_tau['confidence_level'],
#             colorscale=color_scale_decr,
#             cmin=0,
#             cmax=1,
#             colorbar = dict(title='Confidence - Decr Trend', y=0.25, len=0.5),
# #                 showscale=True,
)
                           
traces.append(trace)

# trace = go.Scattermapbox(
#         mode='markers',
#         lon = stat_mf_neg_tau['long'],
#         lat = stat_mf_neg_tau['lat'],
#         text = stat_mf_neg_tau['site_name'],
# #             textposition='top right',
# #             textfont=dict(
# #                 size=20,
# #                 color='black'
#         customdata=stat_mf_neg_tau[['sites','confidence_level','tau','trend','site_name']],
#         hovertemplate = 
#            '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>Confidence Level: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#         name = 'Modified Flows - neg trending',
#         showlegend=False,
#         marker=go.scattermapbox.Marker(
#             size=10,
#             color=stat_mf_neg_tau['confidence_level'],
#             colorscale=color_scale_decr,
#             cmin=0,
#             cmax=1,
# #             colorbar = dict(title='p values'),
# #                 showscale=True,
#             symbol='circle-stroked'
#         )
# )
# traces.append(trace)  


# # increasing----------------------------------------------   
  
# trace = go.Scattermapbox(
#         mode='markers',
#         lon = stat_hw_pos_tau['long'],
#         lat = stat_hw_pos_tau['lat'],
# #                 name = stat['trend'],
#         text = stat_hw_pos_tau['site_name'],
# #             textposition='top right',
# #             textfont=dict(
# #                 size=20,
# #                 color='black'
#         customdata=stat_hw_pos_tau[['sites','confidence_level','tau','trend','site_name']],
#         hovertemplate = 
#            '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>Confidence Level: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#         name = 'USGS sites - pos trending',
#         showlegend=False,
#         marker=go.scattermapbox.Marker(
#             size=6,
#             color=stat_hw_pos_tau['confidence_level'],
#             colorscale=color_scale_incr,
#             cmin=0,
#             cmax=1,
# #             colorbar = dict(title='p values'),
# #                 showscale=True,
#             symbol=['square' for i in stat_hw_pos_tau.index],
#         )
# )
# traces.append(trace)


# trace = go.Scattermapbox(
#         mode='markers',
#         lon = stat_mf_pos_tau['long'],
#         lat = stat_mf_pos_tau['lat'],
# #                 name = stat['trend'],
#         text = stat_mf_pos_tau['site_name'],
# #             textposition='top right',
# #             textfont=dict(
# #                 size=20,
# #                 color='black'
#         customdata=stat_mf_pos_tau[['sites','confidence_level','tau','trend','site_name']],
#         hovertemplate = 
#            '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>Confidence Level: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#         name = 'Modified Flows - pos trending',
#         showlegend=False,
#         marker=go.scattermapbox.Marker(
#             size=11,
#             color=stat_mf_pos_tau['confidence_level'],
#             colorscale=color_scale_incr,
#             cmin=0,
#             cmax=1,
#             colorbar = dict(title='Confidence - Incr Trend', len=0.5,y=.77),
# #                 showscale=True,
#             symbol=['square' for i in stat_mf_pos_tau.index],

#     ))
# traces.append(trace) 


#--------- purely to get grey symbols on legend ----------
#Just ploting one single point that is without a trend (p>0.6) and then using these traces for the legend.

# stat_hw_nuetral = stat_hw[stat_hw["p"]>.6].iloc[0,:]
# trace = go.Scattermapbox(
#         mode='markers',
#         lon = [stat_hw_nuetral['long']],
#         lat = [stat_hw_nuetral['lat']],
# #                 name = stat['trend'],
#         text = [stat_hw_nuetral['site_name']],
# #             textposition='top right',
# #             textfont=dict(
# #                 size=20,
# #                 color='black'
#         customdata=stat_hw_nuetral[['sites','confidence_level','tau','trend','site_name']],
#         hovertemplate = 
#            '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>Confidence Level: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#         name = 'USGS Sites',
#         showlegend=True,
#         marker=go.scattermapbox.Marker(
#             size=5,
#             color='grey',
#             colorscale=color_scale_incr,
#             cmin=0,
#             cmax=1,
#             symbol='circle',
#     ))
# traces.append(trace) 

# stat_mf_nuetral = stat_mf[stat_mf["p"]>.6].iloc[0,:]
# trace = go.Scattermapbox(
#         mode='markers',
#         lon = [stat_mf_nuetral['long']],
#         lat = [stat_mf_nuetral['lat']],
# #                 name = stat['trend'],
#         text = [stat_mf_nuetral['site_name']],
# #             textposition='top right',
# #             textfont=dict(
# #                 size=20,
# #                 color='black'
#         customdata=stat_mf_nuetral[['sites','confidence_level','tau','trend','site_name']],
#         hovertemplate = 
#            '<b>%{text}</b><br>ID : %{customdata[0]}<br>Trend: %{customdata[3]}<br>Confidence Level: %{customdata[1]:.2f}<br>tau: %{customdata[2]:.2f}<br><extra></extra>', # extra removes trace information
#         name = 'Modified Flows',
#         showlegend=True,
#         marker=go.scattermapbox.Marker(
#             size=11,
#             color='grey',
#             colorscale=color_scale_incr,
#             cmin=0,
#             cmax=1,
#             symbol='circle',
#     ))
# traces.append(trace) 


#------------
  
layout = go.Layout(
#     mapbox_layers=[
#         {
#             "below": 'traces',
#             "sourcetype": "raster",
#             "sourceattribution": "United States Geological Survey",
#             "source": [
#                 "https://basemap.nationalmap.gov/arcgis/rest/services/USGSHydroCached/MapServer/tile/{z}/{y}/{x}"
#             ],
#         }
#     ],        
    mapbox = {
#         'style': "stamen-terrain",
        'style':'outdoors',
#         'style': 'carto-positron',  
        'zoom':4,
        'center': go.layout.mapbox.Center(lat=46.1, lon=-117.5)
    },
    title=f'<b>{title}</b>',
    showlegend=True,
    legend=dict(x=0.5, y=0, traceorder='normal', orientation = 'h'),
    autosize=True,
    width=900,
    height=700
)

fig = go.Figure(data=traces, layout=layout)
fig.show()

In [ ]:
stat_hw_nuetral

In [ ]:
stat

In [ ]:
stat_hw[stat_hw['sites']==13338500]

In [ ]:
stat_hw[stat_hw["p"]>.6].iloc[0,:]